using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace ZadanieTimer
{
    //------------------------------------------------------------------------------
    // <auto-generated>
    //     Ten kod został wygenerowany przez narzędzie.
    //     Wersja wykonawcza:4.0.30319.544
    //
    //     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
    //     kod zostanie ponownie wygenerowany.
    // </auto-generated>
    //------------------------------------------------------------------------------

    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Collections;

    // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 


    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Sprawy:INotifyPropertyChanged
    {

        private SprawaWgPowoda[] sprawaWgPowodaField;
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(PropertyChangedEventArgs args)
        {
            PropertyChangedEventHandler handler = this.PropertyChanged;
            if (handler != null)
            {
                handler(this, args);
            }
        }
        private void OnPropertyChanged(string propertyName)
        {
            this.OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("SprawaWgPowoda")]
        public SprawaWgPowoda[] SprawaWgPowoda
        {
            get
            {
                return this.sprawaWgPowodaField;
            }
            set
            {
                this.sprawaWgPowodaField = value;
            }
        }

    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class SprawaWgPowoda
    {

        private Dowod[] dowodField;

        private string oznaczenieField;
       
        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute("Dowod")]
        public Dowod[] Dowod
        {
            get
            {
                return this.dowodField;
            }
            set
            {
                this.dowodField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string oznaczenie
        {
            get
            {
                return this.oznaczenieField;
            }
            set
            {
                this.oznaczenieField = value;
            }
        }
    }

    /// <uwagi/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Dowod
    {

        private string fakturaField;

        private System.DateTime dataPlatnosciField;

        private decimal kapitalField;

        private decimal odsetkiField;

        private string dataOdField;

        private string dataDoField;

        private sbyte idField;

        /// <uwagi/>
        public string Faktura
        {
            get
            {
                return this.fakturaField;
            }
            set
            {
                this.fakturaField = value;
            }
        }

        /// <uwagi/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime DataPlatnosci
        {
            get
            {
                return this.dataPlatnosciField;
            }
            set
            {
                this.dataPlatnosciField = value;
            }
        }

        /// <uwagi/>
        public decimal Kapital
        {
            get
            {
                return this.kapitalField;
            }
            set
            {
                this.kapitalField = value;
            }
        }

        /// <uwagi/>
        public decimal Odsetki
        {
            get
            {
                return this.odsetkiField;
            }
            set
            {
                this.odsetkiField = value;
            }
        }

        /// <uwagi/>
        /// 
        
        public string DataOd
        {
            get
            {
                return this.dataOdField;
            }
            set
            {
                this.dataOdField = value;
            }
        }

        /// <uwagi/>
        /// 
        
        public string DataDo
        {
            get
            {
                return this.dataDoField;
            }
            set
            {
                this.dataDoField = value;
            }
        }

        /// <uwagi/>
        public sbyte Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }

   

}
