//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DokOdebr
    {
        public DokOdebr()
        {
            this.DokumentKomunikacjaEPU = new HashSet<DokumentKomunikacjaEPU>();
            this.PdfStore = new HashSet<PdfStore>();
        }
    
        public int Id { get; set; }
        public int PartitionKey { get; set; }
        public Nullable<System.DateTime> DataRejestracji { get; set; }
        public Nullable<System.DateTime> DataDokumentu { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> Format { get; set; }
        public byte[] Bin { get; set; }
        public Nullable<int> IdWiena { get; set; }
        public Nullable<short> CzyZalatw { get; set; }
        public Nullable<System.DateTime> DataZalatwienia { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public string kreator { get; set; }
        public string modyfikator { get; set; }
        public Nullable<System.DateTime> DDoWieny { get; set; }
        public Nullable<int> Sprawa_id { get; set; }
        public string Tresc { get; set; }
        public Nullable<int> CzyEPU { get; set; }
        public Nullable<int> KontoEPU_Id { get; set; }
        public string StatusDok { get; set; }
        public Nullable<int> IdEPU { get; set; }
        public string TrescHtml { get; set; }
        public Nullable<int> TypDok { get; set; }
        public Nullable<int> IsChecked { get; set; }
    
        public virtual ICollection<DokumentKomunikacjaEPU> DokumentKomunikacjaEPU { get; set; }
        public virtual Sprawa Sprawa { get; set; }
        public virtual ICollection<PdfStore> PdfStore { get; set; }
    }
}
