//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DokumentKomunikacjaEPU
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<int> czyus { get; set; }
        public Nullable<int> DokOdebr_Id { get; set; }
        public Nullable<int> NakazOutputElementModels_Id { get; set; }
        public Nullable<int> OrzeczenieOutputElementModels_Id { get; set; }
        public Nullable<int> OrzeczenieVer2OutputElementModel_Id { get; set; }
        public Nullable<int> DokumentOutputElementModels_Id { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual NakazOutputElementModels NakazOutputElementModels { get; set; }
        public virtual OrzeczenieVer2OutputElementModel OrzeczenieVer2OutputElementModel { get; set; }
        public virtual DokumentOutputElementModels DokumentOutputElementModels { get; set; }
        public virtual DokOdebr DokOdebr { get; set; }
    }
}
