//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DokumentWysKomunikacjaEPU
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<int> czyus { get; set; }
        public Nullable<int> DokWys_Id { get; set; }
        public Nullable<int> DokumentOutputElementModels_Id { get; set; }
        public Nullable<int> PozewOutputElementModels_Id { get; set; }
        public Nullable<int> ZazalenieOutputElementModel_Id { get; set; }
        public Nullable<int> SkargaOutputElementModels_Id { get; set; }
        public Nullable<int> WniosekOutputElementModels_Id { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual ZlozDokumentyOutputElementModels ZlozDokumentyOutputElementModels { get; set; }
        public virtual ZlozPozewOutputElementModels ZlozPozewOutputElementModels { get; set; }
        public virtual ZlozSkargiOutputElementModels ZlozSkargiOutputElementModels { get; set; }
        public virtual ZlozWnioskiOutputElementModels ZlozWnioskiOutputElementModels { get; set; }
        public virtual ZlozZazalenieOutputElementModels ZlozZazalenieOutputElementModels { get; set; }
        public virtual DokWys DokWys { get; set; }
    }
}
