//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DokumentOutputElementModels
    {
        public DokumentOutputElementModels()
        {
            this.DokumentKomunikacjaEPU = new HashSet<DokumentKomunikacjaEPU>();
        }
    
        public int Id { get; set; }
        public int IdDokumentu { get; set; }
        public System.DateTime DataDokumentu { get; set; }
        public Nullable<System.DateTime> DataZakreslenia { get; set; }
        public string SygnaturaSprawy { get; set; }
        public string SygnaturaWgPowoda { get; set; }
        public Nullable<int> MojePismaOutputDataModels_Id { get; set; }
    
        public virtual ICollection<DokumentKomunikacjaEPU> DokumentKomunikacjaEPU { get; set; }
        public virtual MojePismaOutputDataModels MojePismaOutputDataModels { get; set; }
    }
}
