//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DokWys
    {
        public DokWys()
        {
            this.DokKomunikacja = new HashSet<DokKomunikacja>();
            this.DokumentPaczka = new HashSet<DokumentPaczka>();
            this.DokumentWysKomunikacjaEPU = new HashSet<DokumentWysKomunikacjaEPU>();
            this.Pozew = new HashSet<Pozew>();
            this.PdfStore = new HashSet<PdfStore>();
        }
    
        public int Id { get; set; }
        public int PartitionKey { get; set; }
        public int TypDok { get; set; }
        public string Nazwa { get; set; }
        public Nullable<System.DateTime> DataDok { get; set; }
        public int StatusDok { get; set; }
        public Nullable<int> IdPaczki { get; set; }
        public Nullable<int> RodzajDok { get; set; }
        public string Opis { get; set; }
        public Nullable<int> Sprawa_id { get; set; }
        public string Tresc { get; set; }
        public Nullable<decimal> WPS { get; set; }
        public Nullable<decimal> Koszty { get; set; }
        public Nullable<int> KontoEPU_Id { get; set; }
        public Nullable<System.DateTime> DataPrawomoc { get; set; }
        public Nullable<System.DateTime> DataOdbioru { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public string kreator { get; set; }
        public string modyfikator { get; set; }
        public Nullable<decimal> Kzp { get; set; }
        public Nullable<decimal> InneKoszty { get; set; }
        public Nullable<decimal> NotyOdsetkowe { get; set; }
        public Nullable<decimal> OdsetkiKapital { get; set; }
        public string TrescHtml { get; set; }
        public string OdsNalicz { get; set; }
        public Nullable<int> Komornik_Id { get; set; }
    
        public virtual ICollection<DokKomunikacja> DokKomunikacja { get; set; }
        public virtual ICollection<DokumentPaczka> DokumentPaczka { get; set; }
        public virtual ICollection<DokumentWysKomunikacjaEPU> DokumentWysKomunikacjaEPU { get; set; }
        public virtual KontoEPU KontoEPU { get; set; }
        public virtual Sprawa Sprawa { get; set; }
        public virtual ICollection<Pozew> Pozew { get; set; }
        public virtual ICollection<PdfStore> PdfStore { get; set; }
    }
}
