//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoreczenieVer2OutputElementModel
    {
        public int Id { get; set; }
        public int IdDoreczeniaVer2 { get; set; }
        public Nullable<System.DateTime> DataDoreczenia { get; set; }
        public System.DateTime DataWyslania { get; set; }
        public Nullable<int> IdNakazu { get; set; }
        public Nullable<int> IdOrzeczenia { get; set; }
        public string Opis { get; set; }
        public string SygnaturaSprawy { get; set; }
        public string SygnaturaWgPowoda { get; set; }
        public Nullable<int> MojeDoreczeniaVer2OutputDataModels_Id { get; set; }
    
        public virtual MojeDoreczeniaVer2OutputDataModel MojeDoreczeniaVer2OutputDataModel { get; set; }
    }
}
