//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class KontoEPU
    {
        public KontoEPU()
        {
            this.Paczka = new HashSet<Paczka>();
            this.DokWys = new HashSet<DokWys>();
        }
    
        public int Id { get; set; }
        public int PartitionKey { get; set; }
        public string NazwaKonta { get; set; }
        public int CzyZawodowy { get; set; }
        public string Pelnomocnictwo { get; set; }
        public string Imie { get; set; }
        public string Imie2 { get; set; }
        public string Nazwisko { get; set; }
        public string PESEL { get; set; }
        public string Stanowisko { get; set; }
        public string Nazwa { get; set; }
        public string LoginEPU { get; set; }
        public string EPUPasswd { get; set; }
        public string kraj { get; set; }
        public string wojewodztwo { get; set; }
        public string powiat { get; set; }
        public string gmina { get; set; }
        public string poczta { get; set; }
        public string miejscowosc { get; set; }
        public string ulica { get; set; }
        public string numer_domu { get; set; }
        public string numer_mieszkania { get; set; }
        public string kod_pocztowy { get; set; }
        public string instytucja { get; set; }
        public string APIKey { get; set; }
        public Nullable<int> JednostkaWindykacji_Id { get; set; }
        public Nullable<int> Czyaktywne { get; set; }
    
        public virtual ICollection<Paczka> Paczka { get; set; }
        public virtual ICollection<DokWys> DokWys { get; set; }
    }
}
