//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MojeOrzeczeniaVer2OutputDataModel
    {
        public MojeOrzeczeniaVer2OutputDataModel()
        {
            this.OrzeczenieVer2OutputElementModel = new HashSet<OrzeczenieVer2OutputElementModel>();
        }
    
        public int Id { get; set; }
        public string Informacja { get; set; }
        public int IloscWszystkichElementow { get; set; }
        public string Opis { get; set; }
    
        public virtual ICollection<OrzeczenieVer2OutputElementModel> OrzeczenieVer2OutputElementModel { get; set; }
    }
}
