//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MojeDoreczeniaVer2OutputDataModel
    {
        public MojeDoreczeniaVer2OutputDataModel()
        {
            this.DoreczenieVer2OutputElementModel = new HashSet<DoreczenieVer2OutputElementModel>();
        }
    
        public int Id { get; set; }
        public string Informacja { get; set; }
        public int IloscWszystkichElementow { get; set; }
        public string Opis { get; set; }
    
        public virtual ICollection<DoreczenieVer2OutputElementModel> DoreczenieVer2OutputElementModel { get; set; }
    }
}
