//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NakazOutputElementModels
    {
        public NakazOutputElementModels()
        {
            this.DokumentKomunikacjaEPU = new HashSet<DokumentKomunikacjaEPU>();
        }
    
        public int Id { get; set; }
        public int IdNakazu { get; set; }
        public System.DateTime DataOrzeczenia { get; set; }
        public Nullable<System.DateTime> DataPrawomocnosci { get; set; }
        public string DokumentXML { get; set; }
        public int KodDecyzji { get; set; }
        public string StatusDokumentu { get; set; }
        public string SygnaturaSprawy { get; set; }
        public string SygnaturaWgPowoda { get; set; }
        public Nullable<int> MojeNakazyOutputDataModels_Id { get; set; }
    
        public virtual ICollection<DokumentKomunikacjaEPU> DokumentKomunikacjaEPU { get; set; }
        public virtual MojeNakazyOutputDataModels MojeNakazyOutputDataModels { get; set; }
    }
}
