//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Naleznosc
    {
        public int Id { get; set; }
        public int PartitionKey { get; set; }
        public Nullable<int> numer { get; set; }
        public Nullable<decimal> kwota { get; set; }
        public Nullable<System.DateTime> data_dok { get; set; }
        public Nullable<int> waluta { get; set; }
        public Nullable<int> TypRoszczenia { get; set; }
        public Nullable<int> TypNal { get; set; }
        public string opis { get; set; }
        public Nullable<int> CzyOdsetki { get; set; }
        public string opis2 { get; set; }
        public Nullable<int> CzySolidarnie { get; set; }
        public Nullable<System.DateTime> data_n { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public string kreator { get; set; }
        public string modyfikator { get; set; }
        public Nullable<int> IdWiena { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<int> Sprawa_id { get; set; }
        public Nullable<int> TypNaleznosci_id { get; set; }
        public Nullable<int> CzyNowa { get; set; }
        public Nullable<decimal> zaleglosc { get; set; }
        public Nullable<System.DateTime> dataWezwania { get; set; }
    
        public virtual Sprawa Sprawa { get; set; }
    }
}
