//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NazwaStatusu
    {
        public NazwaStatusu()
        {
            this.StatusSprawy = new HashSet<StatusSprawy>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> IdWiena { get; set; }
        public Nullable<int> Krok { get; set; }
    
        public virtual ICollection<StatusSprawy> StatusSprawy { get; set; }
    }
}
