//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrzeczenieVer2OutputElementModel
    {
        public OrzeczenieVer2OutputElementModel()
        {
            this.DokumentKomunikacjaEPU = new HashSet<DokumentKomunikacjaEPU>();
        }
    
        public int Id { get; set; }
        public int IdOrzeczeia { get; set; }
        public Nullable<System.DateTime> DataKlauzuli { get; set; }
        public System.DateTime DataOrzeczenia { get; set; }
        public Nullable<System.DateTime> DataPrawomocnosci { get; set; }
        public string DokumentXML { get; set; }
        public Nullable<int> Id_klauzula { get; set; }
        public string KodKlauzuli { get; set; }
        public string NazwaDecyzji { get; set; }
        public string Status { get; set; }
        public string SygnaturaSprawy { get; set; }
        public string SygnaturaWgPowoda { get; set; }
        public int Instancja { get; set; }
        public Nullable<int> MojeOrzeczeniaVer2OutputDataModels_Id { get; set; }
    
        public virtual ICollection<DokumentKomunikacjaEPU> DokumentKomunikacjaEPU { get; set; }
        public virtual MojeOrzeczeniaVer2OutputDataModel MojeOrzeczeniaVer2OutputDataModel { get; set; }
    }
}
