//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaczkaKomunikacja
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DataPrzeslania { get; set; }
        public Nullable<int> Status { get; set; }
        public string OpisTransmisji { get; set; }
        public Nullable<int> Paczka_Id { get; set; }
    
        public virtual Paczka Paczka { get; set; }
    }
}
