//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paczka
    {
        public Paczka()
        {
            this.PaczkaKomunikacja = new HashSet<PaczkaKomunikacja>();
            this.DokumentPaczka = new HashSet<DokumentPaczka>();
        }
    
        public int Id { get; set; }
        public string Oznaczenie { get; set; }
        public Nullable<System.DateTime> DataZalozenia { get; set; }
        public Nullable<System.DateTime> DataWyslania { get; set; }
        public string kreator { get; set; }
        public string modyfikator { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public Nullable<int> czyus { get; set; }
        public Nullable<int> nr { get; set; }
        public Nullable<int> rok { get; set; }
        public Nullable<int> miesiac { get; set; }
        public Nullable<int> StatusPaczki { get; set; }
        public Nullable<int> TypDok { get; set; }
        public Nullable<int> KontoEPU_Id { get; set; }
        public Nullable<int> CzyZestaw { get; set; }
    
        public virtual ICollection<PaczkaKomunikacja> PaczkaKomunikacja { get; set; }
        public virtual ICollection<DokumentPaczka> DokumentPaczka { get; set; }
        public virtual KontoEPU KontoEPU { get; set; }
    }
}
