//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pozew
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DataZlozenia { get; set; }
        public Nullable<decimal> WPS { get; set; }
        public Nullable<decimal> Koszty { get; set; }
        public string Tresc { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public string kreator { get; set; }
        public string modyfikator { get; set; }
        public Nullable<int> DokWys_Id { get; set; }
    
        public virtual DokWys DokWys { get; set; }
    }
}
