//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radca
    {
        public Radca()
        {
            this.Sprawa = new HashSet<Sprawa>();
        }
    
        public int Id { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Tytul { get; set; }
        public Nullable<int> IdWiena { get; set; }
        public string Pesel { get; set; }
    
        public virtual ICollection<Sprawa> Sprawa { get; set; }
    }
}
