//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SprawaOutputElementModels
    {
        public SprawaOutputElementModels()
        {
            this.SprawaKomunikacjaEPU = new HashSet<SprawaKomunikacjaEPU>();
        }
    
        public int Id { get; set; }
        public int IdSprawy { get; set; }
        public Nullable<System.DateTime> DataPrawomocnosci { get; set; }
        public Nullable<System.DateTime> DataWplywu { get; set; }
        public Nullable<System.DateTime> DataZakreslenia { get; set; }
        public Nullable<decimal> KwotaSporu { get; set; }
        public string RolaWSprawie { get; set; }
        public string StanSprawy { get; set; }
        public string StronyWSprawie { get; set; }
        public string SygnaturaWgPowoda { get; set; }
        public string SygnaturaSprawy { get; set; }
        public Nullable<int> MojeSprawyOutputDataModels_Id { get; set; }
    
        public virtual MojeSprawyOutputDataModels MojeSprawyOutputDataModels { get; set; }
        public virtual ICollection<SprawaKomunikacjaEPU> SprawaKomunikacjaEPU { get; set; }
    }
}
