//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sprawa
    {
        public Sprawa()
        {
            this.SprawaKomunikacjaEPU = new HashSet<SprawaKomunikacjaEPU>();
            this.DokWys = new HashSet<DokWys>();
            this.StatusSprawy = new HashSet<StatusSprawy>();
            this.Termin = new HashSet<Termin>();
            this.DokOdebr = new HashSet<DokOdebr>();
            this.Naleznosc = new HashSet<Naleznosc>();
        }
    
        public int id { get; set; }
        public int PartitionKey { get; set; }
        public string sygnatura { get; set; }
        public Nullable<System.DateTime> DataR { get; set; }
        public Nullable<System.DateTime> DataKon { get; set; }
        public int Rok { get; set; }
        public int Poz { get; set; }
        public Nullable<int> CzyKoniec { get; set; }
        public string NrEwid { get; set; }
        public Nullable<int> IdSymbol { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public string kreator { get; set; }
        public string modyfikator { get; set; }
        public Nullable<int> czyus { get; set; }
        public Nullable<int> LiczPrzedplat { get; set; }
        public string LicznikMiejsce { get; set; }
        public string LicznikUlica { get; set; }
        public string Skrot { get; set; }
        public Nullable<int> IdWiena { get; set; }
        public string Uwagi { get; set; }
        public Nullable<int> Radca_Id { get; set; }
        public Nullable<int> JednostkaOrgOddzial_Id { get; set; }
        public Nullable<int> JednostkaOrgRejon_Id { get; set; }
        public Nullable<decimal> WPS { get; set; }
        public string SygnNCe { get; set; }
        public Nullable<System.DateTime> DataZloPozwu { get; set; }
        public Nullable<int> IdSprawyEPU { get; set; }
        public Nullable<decimal> KosztyZadane { get; set; }
        public Nullable<decimal> KosztyZasadzone { get; set; }
        public Nullable<decimal> KosztyPrawomocne { get; set; }
        public Nullable<decimal> KzpZadane { get; set; }
        public Nullable<decimal> KzpZasadzone { get; set; }
        public Nullable<decimal> KzpPrawomocne { get; set; }
        public Nullable<decimal> InneZadane { get; set; }
        public Nullable<decimal> InneZasadzone { get; set; }
        public Nullable<decimal> InnePrawomocne { get; set; }
    
        public virtual ICollection<SprawaKomunikacjaEPU> SprawaKomunikacjaEPU { get; set; }
        public virtual ICollection<DokWys> DokWys { get; set; }
        public virtual ICollection<StatusSprawy> StatusSprawy { get; set; }
        public virtual ICollection<Termin> Termin { get; set; }
        public virtual ICollection<DokOdebr> DokOdebr { get; set; }
        public virtual Radca Radca { get; set; }
        public virtual ICollection<Naleznosc> Naleznosc { get; set; }
    }
}
