//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class SprawaKomunikacjaEPU
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<int> czyus { get; set; }
        public Nullable<int> Sprawa_Id { get; set; }
        public Nullable<int> SprawaOutputElementModels_Id { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Zadanie_Id { get; set; }
    
        public virtual SprawaOutputElementModels SprawaOutputElementModels { get; set; }
        public virtual Sprawa Sprawa { get; set; }
    }
}
