//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusSprawy
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DataStatusu { get; set; }
        public Nullable<int> NazwaStatusu_Id { get; set; }
        public Nullable<int> Sprawa_id { get; set; }
        public Nullable<int> CzyWiena { get; set; }
        public Nullable<System.DateTime> DataWiena { get; set; }
        public Nullable<int> czyus { get; set; }
        public Nullable<int> ExtraStat { get; set; }
    
        public virtual Sprawa Sprawa { get; set; }
        public virtual NazwaStatusu NazwaStatusu { get; set; }
    }
}
