//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TerminTyp
    {
        public TerminTyp()
        {
            this.Termin = new HashSet<Termin>();
        }
    
        public int Id { get; set; }
        public string Nazwa { get; set; }
        public int Numer { get; set; }
        public Nullable<int> AlertAfterDays { get; set; }
        public Nullable<int> AlertEveryDayInMonth { get; set; }
        public Nullable<int> czyus { get; set; }
    
        public virtual ICollection<Termin> Termin { get; set; }
    }
}
