//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Termin
    {
        public int Id { get; set; }
        public Nullable<int> TerminTyp_Id { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> DataZapisu { get; set; }
        public Nullable<System.DateTime> DataDoWykonania { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DataWykonania { get; set; }
        public Nullable<int> Sprawa_Id { get; set; }
        public Nullable<int> Co { get; set; }
        public Nullable<int> Ref_Id { get; set; }
        public Nullable<int> czyus { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public string kreator { get; set; }
        public string modyfikator { get; set; }
    
        public virtual Sprawa Sprawa { get; set; }
        public virtual TerminTyp TerminTyp { get; set; }
    }
}
