//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypZadaniaSet
    {
        public TypZadaniaSet()
        {
            this.ZadanieSet = new HashSet<ZadanieSet>();
        }
    
        public int Id { get; set; }
        public string Opis { get; set; }
        public bool RownolegleUruchamianie { get; set; }
    
        public virtual ICollection<ZadanieSet> ZadanieSet { get; set; }
    }
}
