//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LexEnaZadanieEntities : DbContext
    {
        public LexEnaZadanieEntities()
            : base("name=LexEnaZadanieEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TypZadaniaSet> TypZadaniaSet { get; set; }
        public DbSet<ZadanieSet> ZadanieSet { get; set; }
        public DbSet<DokKomunikacja> DokKomunikacja { get; set; }
        public DbSet<Paczka> Paczka { get; set; }
        public DbSet<PaczkaKomunikacja> PaczkaKomunikacja { get; set; }
        public DbSet<DokumentPaczka> DokumentPaczka { get; set; }
        public DbSet<KontoEPU> KontoEPU { get; set; }
        public DbSet<MojeSprawyOutputDataModels> MojeSprawyOutputDataModels { get; set; }
        public DbSet<SprawaKomunikacjaEPU> SprawaKomunikacjaEPU { get; set; }
        public DbSet<SprawaOutputElementModels> SprawaOutputElementModels { get; set; }
        public DbSet<DokumentWysKomunikacjaEPU> DokumentWysKomunikacjaEPU { get; set; }
        public DbSet<ZlozDokumentyOutputElementModels> ZlozDokumentyOutputElementModels { get; set; }
        public DbSet<ZlozPozewOutputElementModels> ZlozPozewOutputElementModels { get; set; }
        public DbSet<ZlozSkargiOutputElementModels> ZlozSkargiOutputElementModels { get; set; }
        public DbSet<ZlozSprzeciwOutputElementModels> ZlozSprzeciwOutputElementModels { get; set; }
        public DbSet<ZlozWnioskiOutputElementModels> ZlozWnioskiOutputElementModels { get; set; }
        public DbSet<ZlozZazalenieOutputElementModels> ZlozZazalenieOutputElementModels { get; set; }
        public DbSet<Sprawa> Sprawa { get; set; }
        public DbSet<DokWys> DokWys { get; set; }
        public DbSet<Pozew> Pozew { get; set; }
        public DbSet<StatusSprawy> StatusSprawy { get; set; }
        public DbSet<NazwaStatusu> NazwaStatusu { get; set; }
        public DbSet<DokumentKomunikacjaEPU> DokumentKomunikacjaEPU { get; set; }
        public DbSet<MojeNakazyOutputDataModels> MojeNakazyOutputDataModels { get; set; }
        public DbSet<NakazOutputElementModels> NakazOutputElementModels { get; set; }
        public DbSet<DoreczenieVer2OutputElementModel> DoreczenieVer2OutputElementModel { get; set; }
        public DbSet<MojeDoreczeniaVer2OutputDataModel> MojeDoreczeniaVer2OutputDataModel { get; set; }
        public DbSet<MojeOrzeczeniaVer2OutputDataModel> MojeOrzeczeniaVer2OutputDataModel { get; set; }
        public DbSet<OrzeczenieVer2OutputElementModel> OrzeczenieVer2OutputElementModel { get; set; }
        public DbSet<TerminTyp> TerminTyp { get; set; }
        public DbSet<Termin> Termin { get; set; }
        public DbSet<DokumentOutputElementModels> DokumentOutputElementModels { get; set; }
        public DbSet<KancelariaKomornicza> KancelariaKomornicza { get; set; }
        public DbSet<DokOdebr> DokOdebr { get; set; }
        public DbSet<PdfStore> PdfStore { get; set; }
        public DbSet<Radca> Radca { get; set; }
        public DbSet<Naleznosc> Naleznosc { get; set; }
        public DbSet<ZlozPozewOutputDataModels> ZlozPozewOutputDataModels { get; set; }
        public DbSet<ZlozWnioskiOutputDataModels> ZlozWnioskiOutputDataModels { get; set; }
        public DbSet<ZlozDokumentyOutputDataModels> ZlozDokumentyOutputDataModels { get; set; }
        public DbSet<ZlozSkargiOutputDataModels> ZlozSkargiOutputDataModels { get; set; }
        public DbSet<ZlozSprzeciwOutputDataModels> ZlozSprzeciwOutputDataModels { get; set; }
        public DbSet<ZlozZazalenieOutputDataModels> ZlozZazalenieOutputDataModels { get; set; }
        public DbSet<ListaKancelariiKomorniczychOutputElementModels> ListaKancelariiKomorniczychOutputElementModels { get; set; }
        public DbSet<MojeDoreczeniaOutputDataModels> MojeDoreczeniaOutputDataModels { get; set; }
        public DbSet<MojeOrzeczeniaOutputDataModels> MojeOrzeczeniaOutputDataModels { get; set; }
        public DbSet<MojePismaOutputDataModels> MojePismaOutputDataModels { get; set; }
    }
}
