//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZadanieSet
    {
        public int Id { get; set; }
        public string NazwaZadania { get; set; }
        public System.DateTime DataRozpoczęcia { get; set; }
        public int Status { get; set; }
        public string Opis { get; set; }
        public Nullable<System.DateTime> DataZakonczenia { get; set; }
        public int TypZadaniaId { get; set; }
        public string Parametry { get; set; }
        public Nullable<bool> Oczasie { get; set; }
        public Nullable<int> JednostkaWindykacji_Id { get; set; }
    
        public virtual TypZadaniaSet TypZadaniaSet { get; set; }
    }
}
