//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZlozPozewOutputDataModels
    {
        public ZlozPozewOutputDataModels()
        {
            this.ZlozPozewOutputElementModels = new HashSet<ZlozPozewOutputElementModels>();
        }
    
        public int Id { get; set; }
        public decimal LacznaWartoscPrzedmiotowSporu { get; set; }
        public int LiczbaPozwow { get; set; }
        public string OznaczeniaPaczki { get; set; }
        public decimal SumaoplatySadowej { get; set; }
    
        public virtual ICollection<ZlozPozewOutputElementModels> ZlozPozewOutputElementModels { get; set; }
    }
}
