//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZlozSprzeciwOutputElementModels
    {
        public int Id { get; set; }
        public string InformacjaWalidacji { get; set; }
        public int LiczbaPorzadkowa { get; set; }
        public string OpisWalidacji { get; set; }
        public bool Status { get; set; }
        public Nullable<int> ZlozSprzeciwOutputDataModels_Id { get; set; }
    
        public virtual ZlozSprzeciwOutputDataModels ZlozSprzeciwOutputDataModels { get; set; }
    }
}
