//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZadanieTimerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZlozZazalenieOutputDataModels
    {
        public ZlozZazalenieOutputDataModels()
        {
            this.ZlozZazalenieOutputElementModels = new HashSet<ZlozZazalenieOutputElementModels>();
        }
    
        public int Id { get; set; }
        public string OznaczeniaPaczki { get; set; }
        public string Informacja { get; set; }
        public int IloscWszystkichElementow { get; set; }
        public string Opis { get; set; }
    
        public virtual ICollection<ZlozZazalenieOutputElementModels> ZlozZazalenieOutputElementModels { get; set; }
    }
}
