//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NipNetLib.ServiceVat {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01", ConfigurationName="ServiceVat.WeryfikacjaVAT")]
    public interface WeryfikacjaVAT {
        
        // CODEGEN: Generating message contract since the operation SprawdzNIP is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01/" +
            "WeryfikacjaVAT/SprawdzNIP", ReplyAction="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01/" +
            "WeryfikacjaVAT/SprawdzNIPResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NipNetLib.ServiceVat.SprawdzNIPOdpowiedz SprawdzNIP(NipNetLib.ServiceVat.SprawdzNIPZapytanie request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01/" +
            "WeryfikacjaVAT/SprawdzNIP", ReplyAction="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01/" +
            "WeryfikacjaVAT/SprawdzNIPResponse")]
        System.Threading.Tasks.Task<NipNetLib.ServiceVat.SprawdzNIPOdpowiedz> SprawdzNIPAsync(NipNetLib.ServiceVat.SprawdzNIPZapytanie request);
        
        // CODEGEN: Generating message contract since the operation SprawdzNIPNaDzien is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01/" +
            "WeryfikacjaVAT/SprawdzNIPNaDzien", ReplyAction="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01/" +
            "WeryfikacjaVAT/SprawdzNIPNaDzienResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        NipNetLib.ServiceVat.SprawdzNIPNaDzienOdpowiedz SprawdzNIPNaDzien(NipNetLib.ServiceVat.SprawdzNIPNaDzienZapytanie request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01/" +
            "WeryfikacjaVAT/SprawdzNIPNaDzien", ReplyAction="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01/" +
            "WeryfikacjaVAT/SprawdzNIPNaDzienResponse")]
        System.Threading.Tasks.Task<NipNetLib.ServiceVat.SprawdzNIPNaDzienOdpowiedz> SprawdzNIPNaDzienAsync(NipNetLib.ServiceVat.SprawdzNIPNaDzienZapytanie request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01")]
    public partial class TWynikWeryfikacjiVAT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private TKodWeryfikacjiVAT kodField;
        
        private string komunikatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public TKodWeryfikacjiVAT Kod {
            get {
                return this.kodField;
            }
            set {
                this.kodField = value;
                this.RaisePropertyChanged("Kod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Komunikat {
            get {
                return this.komunikatField;
            }
            set {
                this.komunikatField = value;
                this.RaisePropertyChanged("Komunikat");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01")]
    public enum TKodWeryfikacjiVAT {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        Z,
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        X,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SprawdzNIPZapytanie {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01", Order=0)]
        public string NIP;
        
        public SprawdzNIPZapytanie() {
        }
        
        public SprawdzNIPZapytanie(string NIP) {
            this.NIP = NIP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SprawdzNIPOdpowiedz {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01", Order=0)]
        public NipNetLib.ServiceVat.TWynikWeryfikacjiVAT WynikOperacji;
        
        public SprawdzNIPOdpowiedz() {
        }
        
        public SprawdzNIPOdpowiedz(NipNetLib.ServiceVat.TWynikWeryfikacjiVAT WynikOperacji) {
            this.WynikOperacji = WynikOperacji;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SprawdzNIPNaDzienZapytanie {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01", Order=0)]
        public string NIP;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01", Order=1)]
        public System.DateTime Data;
        
        public SprawdzNIPNaDzienZapytanie() {
        }
        
        public SprawdzNIPNaDzienZapytanie(string NIP, System.DateTime Data) {
            this.NIP = NIP;
            this.Data = Data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SprawdzNIPNaDzienOdpowiedz {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.mf.gov.pl/uslugiBiznesowe/uslugiDomenowe/AP/WeryfikacjaVAT/2018/03/01", Order=0)]
        public NipNetLib.ServiceVat.TWynikWeryfikacjiVAT WynikOperacji;
        
        public SprawdzNIPNaDzienOdpowiedz() {
        }
        
        public SprawdzNIPNaDzienOdpowiedz(NipNetLib.ServiceVat.TWynikWeryfikacjiVAT WynikOperacji) {
            this.WynikOperacji = WynikOperacji;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeryfikacjaVATChannel : NipNetLib.ServiceVat.WeryfikacjaVAT, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeryfikacjaVATClient : System.ServiceModel.ClientBase<NipNetLib.ServiceVat.WeryfikacjaVAT>, NipNetLib.ServiceVat.WeryfikacjaVAT {
        
        public WeryfikacjaVATClient() {
        }
        
        public WeryfikacjaVATClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeryfikacjaVATClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeryfikacjaVATClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeryfikacjaVATClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NipNetLib.ServiceVat.SprawdzNIPOdpowiedz NipNetLib.ServiceVat.WeryfikacjaVAT.SprawdzNIP(NipNetLib.ServiceVat.SprawdzNIPZapytanie request) {
            return base.Channel.SprawdzNIP(request);
        }
        
        public NipNetLib.ServiceVat.TWynikWeryfikacjiVAT SprawdzNIP(string NIP) {
            NipNetLib.ServiceVat.SprawdzNIPZapytanie inValue = new NipNetLib.ServiceVat.SprawdzNIPZapytanie();
            inValue.NIP = NIP;
            NipNetLib.ServiceVat.SprawdzNIPOdpowiedz retVal = ((NipNetLib.ServiceVat.WeryfikacjaVAT)(this)).SprawdzNIP(inValue);
            return retVal.WynikOperacji;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipNetLib.ServiceVat.SprawdzNIPOdpowiedz> NipNetLib.ServiceVat.WeryfikacjaVAT.SprawdzNIPAsync(NipNetLib.ServiceVat.SprawdzNIPZapytanie request) {
            return base.Channel.SprawdzNIPAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipNetLib.ServiceVat.SprawdzNIPOdpowiedz> SprawdzNIPAsync(string NIP) {
            NipNetLib.ServiceVat.SprawdzNIPZapytanie inValue = new NipNetLib.ServiceVat.SprawdzNIPZapytanie();
            inValue.NIP = NIP;
            return ((NipNetLib.ServiceVat.WeryfikacjaVAT)(this)).SprawdzNIPAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        NipNetLib.ServiceVat.SprawdzNIPNaDzienOdpowiedz NipNetLib.ServiceVat.WeryfikacjaVAT.SprawdzNIPNaDzien(NipNetLib.ServiceVat.SprawdzNIPNaDzienZapytanie request) {
            return base.Channel.SprawdzNIPNaDzien(request);
        }
        
        public NipNetLib.ServiceVat.TWynikWeryfikacjiVAT SprawdzNIPNaDzien(string NIP, System.DateTime Data) {
            NipNetLib.ServiceVat.SprawdzNIPNaDzienZapytanie inValue = new NipNetLib.ServiceVat.SprawdzNIPNaDzienZapytanie();
            inValue.NIP = NIP;
            inValue.Data = Data;
            NipNetLib.ServiceVat.SprawdzNIPNaDzienOdpowiedz retVal = ((NipNetLib.ServiceVat.WeryfikacjaVAT)(this)).SprawdzNIPNaDzien(inValue);
            return retVal.WynikOperacji;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NipNetLib.ServiceVat.SprawdzNIPNaDzienOdpowiedz> NipNetLib.ServiceVat.WeryfikacjaVAT.SprawdzNIPNaDzienAsync(NipNetLib.ServiceVat.SprawdzNIPNaDzienZapytanie request) {
            return base.Channel.SprawdzNIPNaDzienAsync(request);
        }
        
        public System.Threading.Tasks.Task<NipNetLib.ServiceVat.SprawdzNIPNaDzienOdpowiedz> SprawdzNIPNaDzienAsync(string NIP, System.DateTime Data) {
            NipNetLib.ServiceVat.SprawdzNIPNaDzienZapytanie inValue = new NipNetLib.ServiceVat.SprawdzNIPNaDzienZapytanie();
            inValue.NIP = NIP;
            inValue.Data = Data;
            return ((NipNetLib.ServiceVat.WeryfikacjaVAT)(this)).SprawdzNIPNaDzienAsync(inValue);
        }
    }
}
