//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexEnaTrs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityQuestions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityQuestions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LexEnaTrs.Assets.Resources.SecurityQuestions", typeof(SecurityQuestions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakie jest imię przyjaciela z dzieciństwa?.
        /// </summary>
        public static string BestChildhoodFriendQuestion {
            get {
                return ResourceManager.GetString("BestChildhoodFriendQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jakie nosiłeś(ąś) przezwisko w dziciństwie?.
        /// </summary>
        public static string ChildhoodNicknameQuestion {
            get {
                return ResourceManager.GetString("ChildhoodNicknameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaki był kolor twojego pierwszego samochodu?.
        /// </summary>
        public static string FirstCarColorQuestion {
            get {
                return ResourceManager.GetString("FirstCarColorQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaka była marka twojego pierwszego samochodu?.
        /// </summary>
        public static string FirstCarMakeAndModelQuestion {
            get {
                return ResourceManager.GetString("FirstCarMakeAndModelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W jakim mieście pracowałeś(aś) po raz pierwszy??.
        /// </summary>
        public static string FirstJobCityQuestion {
            get {
                return ResourceManager.GetString("FirstJobCityQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gdzie byłaś(eś) na wakacjach w zeszłym roku?.
        /// </summary>
        public static string LastVacationLocationQuestion {
            get {
                return ResourceManager.GetString("LastVacationLocationQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko twojeje babci?.
        /// </summary>
        public static string MaternalGrandmothersMaidenNameQuestion {
            get {
                return ResourceManager.GetString("MaternalGrandmothersMaidenNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nazwisko panieńskie twojej mamy?.
        /// </summary>
        public static string MothersMaidenNameQuestion {
            get {
                return ResourceManager.GetString("MothersMaidenNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jak się nazywa twoja maskotak?.
        /// </summary>
        public static string PetNameQuestion {
            get {
                return ResourceManager.GetString("PetNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do jakiej szkoły podstawowej uczęszczałaś(ęś)?.
        /// </summary>
        public static string SixthGradeSchoolNameQuestion {
            get {
                return ResourceManager.GetString("SixthGradeSchoolNameQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rok urodzenia twojego taty?.
        /// </summary>
        public static string YearFatherWasBornQuestion {
            get {
                return ResourceManager.GetString("YearFatherWasBornQuestion", resourceCulture);
            }
        }
    }
}
