//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dluz_adresy
    {
        public int ident { get; set; }
        public string miejsce { get; set; }
        public string ulica { get; set; }
        public string kod { get; set; }
        public int id_dluz { get; set; }
        public Nullable<System.DateTime> data_r { get; set; }
        public string miejscowosc { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public Nullable<int> kreator { get; set; }
        public Nullable<int> modyfikator { get; set; }
        public Nullable<int> glowny { get; set; }
        public Nullable<int> koresp { get; set; }
        public Nullable<int> numer_d { get; set; }
        public Nullable<int> numer_l { get; set; }
    }
}
