//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dok_odebr
    {
        public int ident { get; set; }
        public System.DateTime data_r { get; set; }
        public Nullable<int> id_sprawy { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<short> rok { get; set; }
        public Nullable<short> klasa { get; set; }
        public string uwagi { get; set; }
        public Nullable<int> id_dok_typ { get; set; }
        public Nullable<short> czyzalatw { get; set; }
        public Nullable<System.DateTime> d_zalatw { get; set; }
        public string spos_zalatw { get; set; }
        public Nullable<int> id_dok { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public Nullable<int> kreator { get; set; }
        public Nullable<int> modyfikator { get; set; }
        public Nullable<short> czyus { get; set; }
        public Nullable<System.DateTime> d_dok { get; set; }
    
        public virtual dok_odebr_nazwy dok_odebr_nazwy { get; set; }
        public virtual sprawa sprawa { get; set; }
    }
}
