//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dok_odebr_nazwy
    {
        public dok_odebr_nazwy()
        {
            this.dok_odebr = new HashSet<dok_odebr>();
        }
    
        public int ident { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<dok_odebr> dok_odebr { get; set; }
    }
}
