//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class firma
    {
        public firma()
        {
            this.radca = new HashSet<radca>();
            this.sprawa = new HashSet<sprawa>();
        }
    
        public int ident { get; set; }
        public string nazwa { get; set; }
        public string nazwa1 { get; set; }
        public string nazwa2 { get; set; }
        public string ulica { get; set; }
        public string miasto { get; set; }
        public string kod { get; set; }
        public string konto { get; set; }
        public string kasa { get; set; }
        public short typ { get; set; }
        public short aktywna { get; set; }
        public string numer { get; set; }
        public string numer2 { get; set; }
        public Nullable<int> id_oddzial { get; set; }
        public Nullable<int> nr_kod { get; set; }
        public Nullable<short> typ_firmy { get; set; }
        public Nullable<int> myrgb { get; set; }
    
        public virtual ICollection<radca> radca { get; set; }
        public virtual ICollection<sprawa> sprawa { get; set; }
    }
}
