//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class komoall
    {
        public int ident { get; set; }
        public string przy_apel { get; set; }
        public string apelacja { get; set; }
        public string nazwa { get; set; }
        public string rewir { get; set; }
        public string przy_sr { get; set; }
        public string ulica { get; set; }
        public string miasto { get; set; }
        public string kod { get; set; }
        public string tel { get; set; }
        public string zakrewir { get; set; }
        public string komornik { get; set; }
        public string bank { get; set; }
        public string konto { get; set; }
        public string sad_r { get; set; }
        public string email { get; set; }
    }
}
