//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class konto
    {
        public int id { get; set; }
        public string konto1 { get; set; }
        public int ostnr { get; set; }
        public short aktywne { get; set; }
        public Nullable<System.DateTime> data_od { get; set; }
        public Nullable<System.DateTime> data_do { get; set; }
        public string nast_konto { get; set; }
        public string pop_konto { get; set; }
        public string nazwa { get; set; }
        public Nullable<short> typ { get; set; }
        public int id_firmy { get; set; }
        public short rodzaj { get; set; }
        public Nullable<int> schemat_id { get; set; }
        public Nullable<int> zest { get; set; }
        public Nullable<int> saldo { get; set; }
    }
}
