//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class konto_anal
    {
        public konto_anal()
        {
            this.obroty = new HashSet<obroty>();
        }
    
        public int ident { get; set; }
        public int id_konta { get; set; }
        public int numer { get; set; }
        public int id_sprawy { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public Nullable<int> kreator { get; set; }
        public Nullable<int> modyfikator { get; set; }
        public int czyus { get; set; }
        public Nullable<short> czyvat { get; set; }
        public Nullable<decimal> winien_vat0 { get; set; }
        public Nullable<decimal> ma_vat0 { get; set; }
        public int id_firmy { get; set; }
    
        public virtual ICollection<obroty> obroty { get; set; }
    }
}
