//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class koszt
    {
        public int ident { get; set; }
        public int id_sprawy { get; set; }
        public int id_typ_nal { get; set; }
        public Nullable<decimal> kwota { get; set; }
        public Nullable<decimal> zwrot { get; set; }
        public Nullable<System.DateTime> data_n { get; set; }
        public string uwagi { get; set; }
        public string tytul { get; set; }
    
        public virtual sprawa sprawa { get; set; }
        public virtual typ_nal typ_nal { get; set; }
    }
}
