//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nal_stan
    {
        public int ident { get; set; }
        public int id_nal { get; set; }
        public System.DateTime data_s { get; set; }
        public Nullable<decimal> kwota_n { get; set; }
        public Nullable<decimal> kwota_k { get; set; }
        public Nullable<decimal> kwota_o { get; set; }
        public Nullable<decimal> ods_dzien { get; set; }
        public short typ_stan { get; set; }
        public Nullable<short> oblicz { get; set; }
    
        public virtual naleznosc naleznosc { get; set; }
    }
}
