//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class naleznosc
    {
        public naleznosc()
        {
            this.nal_stan = new HashSet<nal_stan>();
            this.ods_sprawy = new HashSet<ods_sprawy>();
            this.wplata_podz = new HashSet<wplata_podz>();
        }
    
        public int ident { get; set; }
        public int id_sprawy { get; set; }
        public int id_typ_nal { get; set; }
        public Nullable<decimal> kwota { get; set; }
        public Nullable<System.DateTime> data_n { get; set; }
        public Nullable<System.DateTime> data_fv { get; set; }
        public bool czy_proc { get; set; }
        public string uwagi { get; set; }
        public string tytul { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public Nullable<int> kreator { get; set; }
        public Nullable<int> modyfikator { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<int> id_naleznosci { get; set; }
        public Nullable<decimal> OZE { get; set; }
        public Nullable<decimal> Przejsciowa { get; set; }
        public Nullable<decimal> Kogeneracyjna { get; set; }
        public Nullable<decimal> Mocowa { get; set; }
        public string Nr_KSEF { get; set; }
        public Nullable<System.DateTime> Data_wys_KSEF { get; set; }
        public Nullable<System.DateTime> Data_prz_KSEF { get; set; }
    
        public virtual ICollection<nal_stan> nal_stan { get; set; }
        public virtual sprawa sprawa { get; set; }
        public virtual typ_nal typ_nal { get; set; }
        public virtual ICollection<ods_sprawy> ods_sprawy { get; set; }
        public virtual ICollection<wplata_podz> wplata_podz { get; set; }
    }
}
