//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class obroty
    {
        public int ident { get; set; }
        public int id_sprawy { get; set; }
        public int id_konta { get; set; }
        public Nullable<System.DateTime> d_operacji { get; set; }
        public string nr_dowodu { get; set; }
        public string nr_teczki { get; set; }
        public Nullable<int> rodzaj { get; set; }
        public Nullable<decimal> winien { get; set; }
        public Nullable<decimal> ma { get; set; }
        public Nullable<decimal> energia { get; set; }
        public Nullable<decimal> koszty { get; set; }
        public Nullable<decimal> odsetki { get; set; }
        public Nullable<decimal> inne { get; set; }
        public Nullable<decimal> vat { get; set; }
        public string uwagi { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public Nullable<int> kreator { get; set; }
        public Nullable<int> modyfikator { get; set; }
        public Nullable<int> czyus { get; set; }
        public string dluznik { get; set; }
        public Nullable<decimal> kzp { get; set; }
        public Nullable<decimal> wpis { get; set; }
        public Nullable<decimal> klauzula { get; set; }
        public Nullable<decimal> kza { get; set; }
        public Nullable<decimal> kl_adw { get; set; }
        public Nullable<decimal> komo { get; set; }
        public Nullable<decimal> inne_sad { get; set; }
        public Nullable<decimal> ods_kapital { get; set; }
        public decimal ods_naliczone { get; set; }
        public Nullable<int> id_schemat { get; set; }
        public Nullable<int> id_poz_schemat { get; set; }
        public Nullable<decimal> wdz { get; set; }
    
        public virtual konto_anal konto_anal { get; set; }
    }
}
