//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ods_sprawy
    {
        public int ident { get; set; }
        public int id_nal { get; set; }
        public Nullable<int> id_typ_ods { get; set; }
        public Nullable<System.DateTime> data_p { get; set; }
        public Nullable<System.DateTime> data_k { get; set; }
        public Nullable<decimal> proc0 { get; set; }
        public string uwagi { get; set; }
        public string kod { get; set; }
    
        public virtual ods_tab_nazwy ods_tab_nazwy { get; set; }
        public virtual naleznosc naleznosc { get; set; }
    }
}
