//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ods_tab_nazwy
    {
        public ods_tab_nazwy()
        {
            this.ods_sprawy = new HashSet<ods_sprawy>();
            this.ods_tab = new HashSet<ods_tab>();
        }
    
        public int ident { get; set; }
        public string nazwa { get; set; }
    
        public virtual ICollection<ods_sprawy> ods_sprawy { get; set; }
        public virtual ICollection<ods_tab> ods_tab { get; set; }
    }
}
