//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pisma_wys
    {
        public int ident { get; set; }
        public Nullable<int> id_nadawcy { get; set; }
        public Nullable<int> id_sprawy { get; set; }
        public string nazwa1 { get; set; }
        public string nazwa2 { get; set; }
        public string nazwa3 { get; set; }
        public string kod_poczt { get; set; }
        public string poczta { get; set; }
        public string ulica { get; set; }
        public Nullable<System.DateTime> data_r { get; set; }
        public string nazwa_pisma { get; set; }
        public Nullable<short> termin { get; set; }
        public string rodzaj { get; set; }
        public string sygnatura { get; set; }
        public Nullable<int> id_dluz { get; set; }
        public Nullable<short> stan { get; set; }
        public Nullable<System.DateTime> data_zwr { get; set; }
        public string uwagi_zwr { get; set; }
        public Nullable<short> czy_zwr { get; set; }
        public Nullable<int> erka { get; set; }
        public string tresc { get; set; }
        public string sygn_psm { get; set; }
        public Nullable<short> odpis { get; set; }
        public Nullable<short> adresat { get; set; }
        public Nullable<int> id_user { get; set; }
        public Nullable<int> id_dok { get; set; }
        public short typ_dok_tresc { get; set; }
        public byte[] tresc_bin { get; set; }
        public int doclen { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public Nullable<int> kreator { get; set; }
        public Nullable<int> modyfikator { get; set; }
        public Nullable<short> czyus { get; set; }
    
        public virtual sprawa sprawa { get; set; }
    }
}
