//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class radca
    {
        public int ident { get; set; }
        public string stanowisko { get; set; }
        public string nazwisko { get; set; }
        public string imie { get; set; }
        public string dodatek { get; set; }
        public int id_pracownik { get; set; }
        public short aktywny { get; set; }
        public string stanowisko_dopelniacz { get; set; }
        public string nazwisko_dopelniacz { get; set; }
        public string imie_dopelniacz { get; set; }
        public short status { get; set; }
        public Nullable<int> id_firmy { get; set; }
        public string PESEL { get; set; }
    
        public virtual firma firma { get; set; }
    }
}
