//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class skazani
    {
        public skazani()
        {
            this.spr_dluz = new HashSet<spr_dluz>();
        }
    
        public int id { get; set; }
        public short osoba_lub_firma { get; set; }
        public string nazwisko { get; set; }
        public string imie { get; set; }
        public string miasto_ur { get; set; }
        public Nullable<System.DateTime> data_ur { get; set; }
        public string imie_ojca { get; set; }
        public string imie_matki { get; set; }
        public Nullable<int> id_adresu { get; set; }
        public Nullable<int> id_adresu_zamel { get; set; }
        public string nazw_pan_matki { get; set; }
        public Nullable<int> key1 { get; set; }
        public string pesel { get; set; }
        public string dowod { get; set; }
        public string nazw_pan { get; set; }
        public string nip { get; set; }
        public string regon { get; set; }
        public string krs { get; set; }
        public string rdzen { get; set; }
        public string uwagi { get; set; }
        public Nullable<int> id_grupy { get; set; }
        public Nullable<int> czyus { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public Nullable<int> kreator { get; set; }
        public Nullable<int> modyfikator { get; set; }
        public string dane_kom { get; set; }
        public Nullable<short> done { get; set; }
        public short rejestr { get; set; }
    
        public virtual ICollection<spr_dluz> spr_dluz { get; set; }
    }
}
