//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class spr_dluz
    {
        public int ident { get; set; }
        public Nullable<int> id_sprawy { get; set; }
        public Nullable<int> id_dluz { get; set; }
    
        public virtual skazani skazani { get; set; }
        public virtual sprawa sprawa { get; set; }
    }
}
