//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class spr_egz
    {
        public int ident { get; set; }
        public int id_sprawy { get; set; }
        public int id_komornik { get; set; }
        public Nullable<System.DateTime> data_wniosku { get; set; }
        public Nullable<System.DateTime> data_uzupeł { get; set; }
        public string km { get; set; }
        public Nullable<System.DateTime> data_umo { get; set; }
        public Nullable<int> przyczyna_umo { get; set; }
        public string przyczyna_umo_opis { get; set; }
        public Nullable<System.DateTime> data_zawiesz { get; set; }
        public Nullable<int> przyczyna_zawiesz { get; set; }
        public string przyczyna_zaw_opis { get; set; }
        public Nullable<System.DateTime> data_post_koszt { get; set; }
        public Nullable<System.DateTime> data_zwrotu { get; set; }
        public Nullable<int> przyczyna_zwrot { get; set; }
        public string przyczyna_zwrot_opis { get; set; }
        public string uwagi { get; set; }
        public int aktualna { get; set; }
        public Nullable<int> czyus { get; set; }
        public Nullable<int> kreator { get; set; }
        public Nullable<int> modyfikator { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public Nullable<decimal> kwota { get; set; }
        public Nullable<decimal> koszty { get; set; }
        public Nullable<decimal> odsetki { get; set; }
        public Nullable<System.DateTime> data_dor_umo { get; set; }
    }
}
