//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class spr_sadowa
    {
        public int ident { get; set; }
        public int id_sprawa { get; set; }
        public int id_sad { get; set; }
        public Nullable<System.DateTime> data_pozwu { get; set; }
        public Nullable<System.DateTime> data_wezw_braki { get; set; }
        public Nullable<System.DateTime> data_nakazu { get; set; }
        public Nullable<System.DateTime> data_sprzeciwu { get; set; }
        public Nullable<System.DateTime> data_zawieszenia { get; set; }
        public Nullable<int> przyczyna_zaw { get; set; }
        public string przyczyna_zaw_opis { get; set; }
        public Nullable<System.DateTime> data_umo { get; set; }
        public Nullable<int> przyczyna_umo { get; set; }
        public string przyczyna_umo_opis { get; set; }
        public Nullable<System.DateTime> data_uchyl_nakazu { get; set; }
        public Nullable<System.DateTime> data_klauzuli { get; set; }
        public Nullable<System.DateTime> data_otrz_nakaz { get; set; }
        public string sygn_nakazowe { get; set; }
        public string sygn_proces { get; set; }
        public Nullable<System.DateTime> data_zwroty_pozw { get; set; }
        public Nullable<System.DateTime> data_ponow_wnies { get; set; }
        public string pracownicy { get; set; }
        public string uwagi { get; set; }
        public Nullable<short> czyus { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public Nullable<int> kreator { get; set; }
        public Nullable<int> modyfikator { get; set; }
        public short aktywne { get; set; }
        public Nullable<System.DateTime> data_wyroku { get; set; }
        public Nullable<System.DateTime> data_otrz_wyr { get; set; }
        public Nullable<System.DateTime> data_wn_klauz { get; set; }
    }
}
