//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sprawa
    {
        public sprawa()
        {
            this.dok_odebr = new HashSet<dok_odebr>();
            this.koszt = new HashSet<koszt>();
            this.pisma_wys = new HashSet<pisma_wys>();
            this.wplata = new HashSet<wplata>();
            this.spr_stan = new HashSet<spr_stan>();
            this.spr_dluz = new HashSet<spr_dluz>();
            this.naleznosc = new HashSet<naleznosc>();
        }
    
        public int ident { get; set; }
        public string sygnatura { get; set; }
        public Nullable<System.DateTime> data_r { get; set; }
        public Nullable<System.DateTime> data_ostatnia { get; set; }
        public Nullable<System.DateTime> data_kon { get; set; }
        public short rok { get; set; }
        public int poz { get; set; }
        public Nullable<short> zakoncz { get; set; }
        public string uwagi { get; set; }
        public string nr_ewid { get; set; }
        public Nullable<int> id_rejon { get; set; }
        public Nullable<int> id_sad { get; set; }
        public Nullable<int> id_radca { get; set; }
        public Nullable<int> id_symbol { get; set; }
        public System.DateTime d_kreacji { get; set; }
        public System.DateTime d_modyfikacji { get; set; }
        public int kreator { get; set; }
        public int modyfikator { get; set; }
        public int czyus { get; set; }
        public Nullable<int> licz_przedplat { get; set; }
        public string licznik_miejsce { get; set; }
        public string licznik_ulica { get; set; }
        public int ksiega { get; set; }
        public string skrot { get; set; }
        public Nullable<short> done { get; set; }
        public short gdzie_akta { get; set; }
        public Nullable<System.DateTime> d_protokolu { get; set; }
        public string faktura { get; set; }
        public Nullable<decimal> kwota { get; set; }
        public string protokol { get; set; }
        public string rodzaj { get; set; }
        public Nullable<System.DateTime> d_faktury { get; set; }
        public Nullable<decimal> korekta { get; set; }
        public Nullable<decimal> prowizja { get; set; }
        public Nullable<decimal> raport { get; set; }
        public Nullable<decimal> prot_kwt { get; set; }
        public int id_firmy { get; set; }
        public Nullable<int> id_radca_egz { get; set; }
        public Nullable<short> licz_czynny { get; set; }
        public string arch_teczka { get; set; }
        public string arch_paczka { get; set; }
        public Nullable<System.DateTime> data_lexena { get; set; }
        public Nullable<int> id_kancelarii { get; set; }
    
        public virtual ICollection<dok_odebr> dok_odebr { get; set; }
        public virtual firma firma { get; set; }
        public virtual ICollection<koszt> koszt { get; set; }
        public virtual ICollection<pisma_wys> pisma_wys { get; set; }
        public virtual ICollection<wplata> wplata { get; set; }
        public virtual ICollection<spr_stan> spr_stan { get; set; }
        public virtual ICollection<spr_dluz> spr_dluz { get; set; }
        public virtual ICollection<naleznosc> naleznosc { get; set; }
    }
}
