//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class status
    {
        public int ident { get; set; }
        public int numer { get; set; }
        public string nazwa { get; set; }
        public short etap { get; set; }
        public Nullable<int> czyus { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public Nullable<int> modyfikator { get; set; }
        public Nullable<int> kreator { get; set; }
        public Nullable<short> bitmap { get; set; }
        public Nullable<short> def_skip { get; set; }
        public string konto { get; set; }
    }
}
