//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class typ_nal
    {
        public typ_nal()
        {
            this.koszt = new HashSet<koszt>();
            this.naleznosc = new HashSet<naleznosc>();
        }
    
        public int ident { get; set; }
        public string nazwa { get; set; }
        public short typ_nal1 { get; set; }
        public short typ_sum { get; set; }
        public bool czy_proc { get; set; }
        public Nullable<int> nr_tab_ods { get; set; }
        public Nullable<bool> czy_mem { get; set; }
        public short czy_vat { get; set; }
        public short czy_ods_kapital { get; set; }
        public Nullable<short> typ_firmy { get; set; }
        public Nullable<int> priorytet { get; set; }
    
        public virtual ICollection<koszt> koszt { get; set; }
        public virtual ICollection<naleznosc> naleznosc { get; set; }
    }
}
