//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_import_Symbole
    {
        public int ident { get; set; }
        public string oznaczenie { get; set; }
        public int id_firmy { get; set; }
        public Nullable<short> typ_firmy { get; set; }
        public int rok { get; set; }
        public int poz { get; set; }
    }
}
