//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_KosztyEgz
    {
        public int kod { get; set; }
        public int konto { get; set; }
        public int konto_anal { get; set; }
        public int winien { get; set; }
        public int ma { get; set; }
        public Nullable<decimal> energia { get; set; }
        public Nullable<decimal> wdz { get; set; }
        public Nullable<decimal> odsetki { get; set; }
        public int komo { get; set; }
        public Nullable<decimal> inne { get; set; }
        public Nullable<decimal> vat { get; set; }
        public Nullable<decimal> ods_kapital { get; set; }
        public Nullable<decimal> kza { get; set; }
        public Nullable<decimal> kl_adw { get; set; }
        public string nr_dowodu { get; set; }
        public int rodzaj { get; set; }
        public Nullable<System.DateTime> DataOper { get; set; }
        public Nullable<decimal> OdsetkiWniosek { get; set; }
        public int id_sprawy { get; set; }
        public int id_obroty { get; set; }
        public int czyus { get; set; }
        public int id_schemat { get; set; }
        public Nullable<decimal> wpis { get; set; }
        public Nullable<decimal> kzp { get; set; }
        public Nullable<decimal> klauzula { get; set; }
        public Nullable<decimal> inne_sad { get; set; }
        public Nullable<decimal> kzaa { get; set; }
        public int koszty { get; set; }
    }
}
