//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class wiena_centralEntities : DbContext
    {
        public wiena_centralEntities()
            : base("name=wiena_centralEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<dok_odebr> dok_odebr { get; set; }
        public DbSet<dok_odebr_nazwy> dok_odebr_nazwy { get; set; }
        public DbSet<konto> konto { get; set; }
        public DbSet<konto_anal> konto_anal { get; set; }
        public DbSet<koszt> koszt { get; set; }
        public DbSet<nal_stan> nal_stan { get; set; }
        public DbSet<obroty> obroty { get; set; }
        public DbSet<ods_sprawy> ods_sprawy { get; set; }
        public DbSet<pisma_wys> pisma_wys { get; set; }
        public DbSet<zlecenia_ksiegowe> zlecenia_ksiegowe { get; set; }
        public DbSet<firma> firma { get; set; }
        public DbSet<vw_KosztyEgz> vw_KosztyEgz { get; set; }
        public DbSet<spr_egz> spr_egz { get; set; }
        public DbSet<spr_sadowa> spr_sadowa { get; set; }
        public DbSet<slow_rodzaj> slow_rodzaj { get; set; }
        public DbSet<status> status { get; set; }
        public DbSet<status_spr> status_spr { get; set; }
        public DbSet<wzor_tree> wzor_tree { get; set; }
        public DbSet<skan> skan { get; set; }
        public DbSet<radca> radca { get; set; }
        public DbSet<sprawa> sprawa { get; set; }
        public DbSet<sad> sad { get; set; }
        public DbSet<wplata_podz> wplata_podz { get; set; }
        public DbSet<komoall> komoall { get; set; }
        public DbSet<wplata> wplata { get; set; }
        public DbSet<spr_stan> spr_stan { get; set; }
        public DbSet<ods_tab> ods_tab { get; set; }
        public DbSet<ods_tab_nazwy> ods_tab_nazwy { get; set; }
        public DbSet<symbol> symbol { get; set; }
        public DbSet<dowod_slownik> dowod_slownik { get; set; }
        public DbSet<vw_import_Symbole> vw_import_Symbole { get; set; }
        public DbSet<dluz_adresy> dluz_adresy { get; set; }
        public DbSet<skazani> skazani { get; set; }
        public DbSet<spr_dluz> spr_dluz { get; set; }
        public DbSet<notki> notki { get; set; }
        public DbSet<xls_import> xls_import { get; set; }
        public DbSet<xls_zalkom_det> xls_zalkom_det { get; set; }
        public DbSet<typ_nal> typ_nal { get; set; }
        public DbSet<naleznosc> naleznosc { get; set; }
    
        public virtual int sp_MergeCases(Nullable<int> idSrc, Nullable<int> idDest)
        {
            var idSrcParameter = idSrc.HasValue ?
                new ObjectParameter("IdSrc", idSrc) :
                new ObjectParameter("IdSrc", typeof(int));
    
            var idDestParameter = idDest.HasValue ?
                new ObjectParameter("IdDest", idDest) :
                new ObjectParameter("IdDest", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MergeCases", idSrcParameter, idDestParameter);
        }
    
        public virtual int sp_RemoveCosts(Nullable<int> idSprawy)
        {
            var idSprawyParameter = idSprawy.HasValue ?
                new ObjectParameter("IdSprawy", idSprawy) :
                new ObjectParameter("IdSprawy", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RemoveCosts", idSprawyParameter);
        }
    }
}
