//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wplata_podz
    {
        public int ident { get; set; }
        public int id_wplaty { get; set; }
        public int id_nal { get; set; }
        public Nullable<decimal> spl_kap { get; set; }
        public Nullable<decimal> spl_ods { get; set; }
        public Nullable<decimal> zal_kap { get; set; }
        public Nullable<decimal> zal_ods { get; set; }
        public Nullable<decimal> spl_vat { get; set; }
        public Nullable<decimal> zal_vat { get; set; }
    
        public virtual wplata wplata { get; set; }
        public virtual naleznosc naleznosc { get; set; }
    }
}
