//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wplata
    {
        public wplata()
        {
            this.wplata_podz = new HashSet<wplata_podz>();
        }
    
        public int ident { get; set; }
        public int id_sprawy { get; set; }
        public int id_kto { get; set; }
        public decimal kwota { get; set; }
        public Nullable<System.DateTime> data_w { get; set; }
        public Nullable<short> algo { get; set; }
        public string uwagi { get; set; }
        public Nullable<int> id_dluz { get; set; }
        public string nr_dowodu { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public Nullable<int> kreator { get; set; }
        public Nullable<int> modyfikator { get; set; }
        public Nullable<decimal> vat { get; set; }
    
        public virtual sprawa sprawa { get; set; }
        public virtual ICollection<wplata_podz> wplata_podz { get; set; }
    }
}
