//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class wzor_tree
    {
        public int ident { get; set; }
        public int parent { get; set; }
        public int itemhandle { get; set; }
        public string label { get; set; }
        public short children { get; set; }
        public string data { get; set; }
        public short pictureindex { get; set; }
        public short number { get; set; }
        public Nullable<int> obsluga { get; set; }
        public Nullable<int> id_status { get; set; }
        public Nullable<int> def_adr { get; set; }
        public Nullable<int> typ_adr { get; set; }
        public Nullable<short> czyods { get; set; }
    }
}
