//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xls_import
    {
        public int ident { get; set; }
        public string nazwa_pliku { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<int> operator_guid { get; set; }
    }
}
