//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class xls_zalkom_det
    {
        public int ident { get; set; }
        public Nullable<int> lp { get; set; }
        public string oddzial { get; set; }
        public string sygnatura { get; set; }
        public string dluznik { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<decimal> kwota { get; set; }
        public string komentarz { get; set; }
        public Nullable<int> sprawa_ident { get; set; }
        public Nullable<short> status { get; set; }
        public Nullable<int> id_import { get; set; }
        public string uwagi { get; set; }
        public Nullable<short> czyus { get; set; }
    }
}
