//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WienaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zlecenia_ksiegowe
    {
        public int ident { get; set; }
        public int kod { get; set; }
        public int konto { get; set; }
        public int konto_anal { get; set; }
        public decimal winien { get; set; }
        public decimal ma { get; set; }
        public decimal energia { get; set; }
        public decimal koszty { get; set; }
        public decimal odsetki { get; set; }
        public decimal inne { get; set; }
        public decimal vat { get; set; }
        public string nr_dowodu { get; set; }
        public int rodzaj { get; set; }
        public System.DateTime d_zlecenia { get; set; }
        public Nullable<System.DateTime> d_ksiegowania { get; set; }
        public int id_sprawy { get; set; }
        public int id_obroty { get; set; }
        public Nullable<int> kreator { get; set; }
        public Nullable<int> modyfikator { get; set; }
        public Nullable<System.DateTime> d_kreacji { get; set; }
        public Nullable<System.DateTime> d_modyfikacji { get; set; }
        public short czyus { get; set; }
        public string opis { get; set; }
        public Nullable<decimal> kzp { get; set; }
        public Nullable<decimal> wpis { get; set; }
        public Nullable<decimal> klauzula { get; set; }
        public Nullable<decimal> kza { get; set; }
        public Nullable<decimal> kl_adw { get; set; }
        public Nullable<decimal> komo { get; set; }
        public Nullable<decimal> inne_sad { get; set; }
        public Nullable<decimal> ods_kapital { get; set; }
        public decimal ods_naliczone { get; set; }
        public Nullable<int> id_schemat { get; set; }
        public Nullable<int> id_wplaty { get; set; }
        public Nullable<int> nr { get; set; }
        public Nullable<decimal> energia_ten { get; set; }
        public Nullable<decimal> koszty_ten { get; set; }
        public Nullable<decimal> odsetki_ten { get; set; }
        public Nullable<decimal> ods_kaptal_ten { get; set; }
        public decimal ods_naliczone_ten { get; set; }
        public Nullable<decimal> ma_ten { get; set; }
        public Nullable<decimal> vat_ten { get; set; }
        public Nullable<decimal> wdz { get; set; }
        public Nullable<decimal> wdz_ten { get; set; }
    }
}
