//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
using System;
using System.Globalization;
using System.Xml.Serialization;
//------------------------------------------------------------------------------
namespace LexEnaTrs.Web.Models
{

   public enum typOdsetek
    {
        Brak = 0,
        Ustawowe = 2,
        UstawoweZaOpoznienie = 8 , 
        Handlowe = 15,
        HandlowePodmiotyLecznicze = 20
        
    }


    public enum typy_Odsetek
    {
        Brak = 0,
        Ustawowe = 2,
        UstawoweZaOpoznienie = 8,
        UstawoweWtransakcjachHandlowych = 15,
        UstawoweDlaPodmiotowLeczniczych = 20

    }

    // 
    // This source code was auto-generated by xsd, Version=4.6.1055.0.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Wplaty
    {

        private LexEnaTrs.Web.Models.Wplata[] wplataField;

        /// <remarks/>
        
        [System.Xml.Serialization.XmlElementAttribute("Wplata")]
        public LexEnaTrs.Web.Models.Wplata[] Wplata
        {
            get
            {
                return this.wplataField;
            }
            set
            {
                this.wplataField = value;
            }
        }
    }

    /// <remarks/>

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Wplata
    {

        private string  nr_kontaField;

        private System.DateTime data_wplatyField;

        private decimal kwota_wplatyField;

        private string sposob_zaksiegowaniaField;

        /// <remarks/>
        public string Nr_konta
        {
            get
            {
                return this.nr_kontaField;
            }
            set
            {
                this.nr_kontaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Data_wplaty
        {
            get
            {
                return this.data_wplatyField;
            }
            set
            {
                this.data_wplatyField = value;
            }
        }

        /// <remarks/>
        public decimal Kwota_wplaty
        {
            get
            {
                return this.kwota_wplatyField;
            }
            set
            {
                this.kwota_wplatyField = value;
            }
        }

        /// <remarks/>
        public string Sposob_zaksiegowania
        {
            get
            {
                return this.sposob_zaksiegowaniaField;
            }
            set
            {
                this.sposob_zaksiegowaniaField = value;
            }
        }
    }

   
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Typ_obciazen_doksiegowanych
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Typ_doksiegowania
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Status
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Sprawy
    {

        private Naglowek naglowekField;

        private Odbiorca[] odbiorcyField;

        /// <remarks/>
        public Naglowek Naglowek
        {
            get
            {
                return this.naglowekField;
            }
            set
            {
                this.naglowekField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Odbiorca", IsNullable = false)]
        public Odbiorca[] Odbiorcy
        {
            get
            {
                return this.odbiorcyField;
            }
            set
            {
                this.odbiorcyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Naglowek
    {

        private string oddzialField;

        private string systemField;

        private Status statusField;

        private string data_i_czas_generowaniaField;

        private Operator operatorField;

        private System.DateTime data_OdField;

        private System.DateTime data_DoField;

        private string typ_obciazeniaField;

        private Typ_obciazen_doksiegowanych typ_obciazen_doksiegowanychField;

        /// <remarks/>
        public string Oddzial
        {
            get
            {
                return this.oddzialField;
            }
            set
            {
                this.oddzialField = value;
            }
        }

        /// <remarks/>
        public string System
        {
            get
            {
                return this.systemField;
            }
            set
            {
                this.systemField = value;
            }
        }

        /// <remarks/>
        public Status Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        public string Data_i_czas_generowania
        {
            get
            {
                return this.data_i_czas_generowaniaField;
            }
            set
            {
                this.data_i_czas_generowaniaField = value;
            }
        }

        /// <remarks/>
        public Operator Operator
        {
            get
            {
                return this.operatorField;
            }
            set
            {
                this.operatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Data_Od
        {
            get
            {
                return this.data_OdField;
            }
            set
            {
                this.data_OdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime Data_Do
        {
            get
            {
                return this.data_DoField;
            }
            set
            {
                this.data_DoField = value;
            }
        }

        /// <remarks/>
        public string Typ_obciazenia
        {
            get
            {
                return this.typ_obciazeniaField;
            }
            set
            {
                this.typ_obciazeniaField = value;
            }
        }

        /// <remarks/>
        public Typ_obciazen_doksiegowanych Typ_obciazen_doksiegowanych
        {
            get
            {
                return this.typ_obciazen_doksiegowanychField;
            }
            set
            {
                this.typ_obciazen_doksiegowanychField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Operator
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Odbiorca
    {

        private string nr_ewidencyjnyField;

        private string nazwaField;

        private Adres adresField;

        private Nazwa_korespondencja nazwa_korespondencjaField;

        private Adres_korespondencyjny adres_korespondencyjnyField;

        private string pESELField;

        private string nIPField;

        private string kRSField;

        private string rEGONField;

        private Obciazenie[] obciazeniaField;

        private Doksiegowania doksiegowaniaField;

        private decimal razem_obciazeniaField;

        private decimal razem_obciazenia_do_zaplatyField;

        private decimal razem_wplatyField;
        private string[] nr_ewidencyjnyArrayField;

        /// <remarks/>
        public string Nr_ewidencyjny
        {
            get
            {
                return this.nr_ewidencyjnyField;
            }
            set
            {
                this.nr_ewidencyjnyField = value;
            }
        }


        public string[] Nr_ewidencyjnyArray
        {
            get
            {
                return this.nr_ewidencyjnyArrayField;
            }
            set
            {
                this.nr_ewidencyjnyArrayField = value;
            }
        }
        /// <remarks/>
        public string Nazwa
        {
            get
            {
                return this.nazwaField;
            }
            set
            {
                this.nazwaField = value;
            }
        }

        /// <remarks/>
      
        public Adres Adres
        {
            get
            {
                return this.adresField;
            }
            set
            {
                this.adresField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public Nazwa_korespondencja Nazwa_korespondencja
        {
            get
            {
                return this.nazwa_korespondencjaField;
            }
            set
            {
                this.nazwa_korespondencjaField = value;
            }
        }

        /// <remarks/>
        public Adres_korespondencyjny Adres_korespondencyjny
        {
            get
            {
                return this.adres_korespondencyjnyField;
            }
            set
            {
                this.adres_korespondencyjnyField = value;
            }
        }

        /// <remarks/>
        public string PESEL
        {
            get
            {
                return this.pESELField;
            }
            set
            {
                this.pESELField = value;
            }
        }

        /// <remarks/>
        public string NIP
        {
            get
            {
                return this.nIPField;
            }
            set
            {
                this.nIPField = value;
            }
        }

        /// <remarks/>
        public string KRS
        {
            get
            {
                return this.kRSField;
            }
            set
            {
                this.kRSField = value;
            }
        }

        /// <remarks/>
        public string REGON
        {
            get
            {
                return this.rEGONField;
            }
            set
            {
                this.rEGONField = value;
            }
        }

        /// <remarks/>
     
        [System.Xml.Serialization.XmlArrayItemAttribute("Obciazenie", IsNullable = false)]
        public Obciazenie[] Obciazenia
        {
            get
            {
                return this.obciazeniaField;
            }
            set
            {
                this.obciazeniaField = value;
            }
        }

        /// <remarks/>
        ///     
 
        public Doksiegowania Doksiegowania
        {
            get
            {
                return this.doksiegowaniaField;
            }
            set
            {
                this.doksiegowaniaField = value;
            }
        }

        /// <remarks/>
        public decimal Razem_obciazenia
        {
            get
            {
                return this.razem_obciazeniaField;
            }
            set
            {
                this.razem_obciazeniaField = value;
            }
        }

        /// <remarks/>
        public decimal Razem_obciazenia_do_zaplaty
        {
            get
            {
                return this.razem_obciazenia_do_zaplatyField;
            }
            set
            {
                this.razem_obciazenia_do_zaplatyField = value;
            }
        }

        /// <remarks/>
        public decimal Razem_wplaty
        {
            get
            {
                return this.razem_wplatyField;
            }
            set
            {
                this.razem_wplatyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Adres
    {

        private string kod_pocztowyField;

        private string miejscowoscField;

        private string pocztaField;

        private string ulicaField;

        private string numer_posesjiField;

        private string numer_domuField;

        /// <remarks/>
        public string Kod_pocztowy
        {
            get
            {
                return this.kod_pocztowyField;
            }
            set
            {
                this.kod_pocztowyField = value;
            }
        }

        /// <remarks/>
        public string Miejscowosc
        {
            get
            {
                return this.miejscowoscField;
            }
            set
            {
                this.miejscowoscField = value;
            }
        }

        /// <remarks/>
        public string Poczta
        {
            get
            {
                return this.pocztaField;
            }
            set
            {
                this.pocztaField = value;
            }
        }

        /// <remarks/>
        public string Ulica
        {
            get
            {
                return this.ulicaField;
            }
            set
            {
                this.ulicaField = value;
            }
        }

        /// <remarks/>
        public string Numer_posesji
        {
            get
            {
                return this.numer_posesjiField;
            }
            set
            {
                this.numer_posesjiField = value;
            }
        }

        /// <remarks/>
        public string Numer_domu
        {
            get
            {
                return this.numer_domuField;
            }
            set
            {
                this.numer_domuField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Nazwa_korespondencja
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Adres_korespondencyjny
    {

        private string kod_pocztowyField;

        private string miejscowoscField;

        private string pocztaField;

        private string ulicaField;

        private string numer_posesjiField;

        private string numer_domuField;

        /// <remarks/>
        public string Kod_pocztowy
        {
            get
            {
                return this.kod_pocztowyField;
            }
            set
            {
                this.kod_pocztowyField = value;
            }
        }

        /// <remarks/>
        public string Miejscowosc
        {
            get
            {
                return this.miejscowoscField;
            }
            set
            {
                this.miejscowoscField = value;
            }
        }

        /// <remarks/>
        public string Poczta
        {
            get
            {
                return this.pocztaField;
            }
            set
            {
                this.pocztaField = value;
            }
        }

        /// <remarks/>
        public string Ulica
        {
            get
            {
                return this.ulicaField;
            }
            set
            {
                this.ulicaField = value;
            }
        }

        /// <remarks/>
        public string Numer_posesji
        {
            get
            {
                return this.numer_posesjiField;
            }
            set
            {
                this.numer_posesjiField = value;
            }
        }

        /// <remarks/>
        public string Numer_domu
        {
            get
            {
                return this.numer_domuField;
            }
            set
            {
                this.numer_domuField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class KRS
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Obciazenie
    {

        private decimal kwota_obciazeniaField;

        private decimal kwota_obciazenia_VATField;

        private decimal kwota_do_zaplatyField;

        private decimal kwota_do_zaplaty_VATField;

        private string nr_dokumentuField;

        private System.DateTime data_wystawienia_dokumentuField;

        private System.DateTime data_platnosciField;

        private string typ_obciazeniaField;

        private string okres_odsetkowy_odField;

        private string okres_odsetkowy_doField;

        private string nr_fakturyField;

        private LexEnaTrs.Web.Models.Wplata[] wplatyField;

        private int? id_sprawyField;

        private string rodzaj_obciazeniaField;

        private typOdsetek typOdsetekField;

        private typy_Odsetek? typ_OdsetekField; 
    
        private decimal ozeField;

        private decimal kogeneracyjnaField;

        private decimal przejsciowaField;

        private decimal mocowaField;

        private string Nr_KSEFField;

        private System.DateTime data_wys_KSEFField;

        private System.DateTime? data_prz_KSEFField;

        private string nr_KSEFField;

        /// <remarks/>
        public int? Id_sprawy
        {
            get {
                return this.id_sprawyField;
            }
            set {
                this.id_sprawyField = value;
            }

        }
        public decimal Kwota_obciazenia
        {
            get
            {
                return this.kwota_obciazeniaField;
            }
            set
            {
                this.kwota_obciazeniaField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public decimal Kwota_obciazenia_VAT
        {
            get
            {
                return this.kwota_obciazenia_VATField;
            }
            set
            {
                this.kwota_obciazenia_VATField = value;
            }
        }
        [XmlElement("Kwota_obciazenia_VAT")]
        public string kwota_obciazenia_VATStr
        {

            get
            {
                return string.Format(CultureInfo.InvariantCulture, "{0:0.00}", Kwota_obciazenia_VAT);  
            }
            set
            {
                decimal result = 0;
                if (decimal.TryParse(value, NumberStyles.Number | NumberStyles.AllowDecimalPoint | NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out result))
                    Kwota_obciazenia_VAT = result;
                else
                    Kwota_obciazenia_VAT = 0;
            }
        }



        /// <remarks/>
        [XmlIgnore]
        public decimal Kwota_do_zaplaty
        {
            get
            {
                return this.kwota_do_zaplatyField;
            }
            set
            {
                this.kwota_do_zaplatyField = value;
            }
        }


        [XmlElement("Kwota_do_zaplaty")]
        public string kwota_do_zaplatyStr
        {

            get
            {
                return string.Format(CultureInfo.InvariantCulture, "{0:0.00}", Kwota_do_zaplaty);
            }
            set
            {
                decimal result = 0;
                if (decimal.TryParse(value, NumberStyles.Number | NumberStyles.AllowDecimalPoint | NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out result))
                    Kwota_do_zaplaty = result;
                else
                    Kwota_do_zaplaty = 0;
            }
        }




        /// <remarks/>
        [XmlIgnore]
        public decimal Kwota_do_zaplaty_VAT
        {
            get
            {
                return this.kwota_do_zaplaty_VATField;
            }
            set
            {
                this.kwota_do_zaplaty_VATField = value;
            }
        }

      
        [XmlElement("Kwota_do_zaplaty_VAT")]
        public string kwota_do_zaplaty_VATSrt
        {

            get
            {
                return string.Format(CultureInfo.InvariantCulture, "{0:0.00}", Kwota_do_zaplaty_VAT);
            }
            set
            {
                decimal result = 0;
                if (decimal.TryParse(value, NumberStyles.Number|NumberStyles.AllowDecimalPoint|NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out result))
                    Kwota_do_zaplaty_VAT = result;
                else
                    Kwota_do_zaplaty_VAT = 0;
            }
       }


        /// <remarks/>
        public string Nr_dokumentu
        {
            get
            {
                return this.nr_dokumentuField;
            }
            set
            {
                this.nr_dokumentuField = value;
            }
        }

        /// <remarks/>
        [XmlIgnore]
        public System.DateTime Data_wystawienia_dokumentu
        {
            get
            {
                return this.data_wystawienia_dokumentuField;
            }
            set
            {
                this.data_wystawienia_dokumentuField = value;
            }
        }

        [XmlElement("Data_wystawienia_dokumentu")]
        public string XmlDateTimeDataWystawieniaDokumentu
        {


            get
            {
                return Data_wystawienia_dokumentu.ToString("yyyy-MM-dd");
            }
            set { Data_wystawienia_dokumentu = DateTime.Parse(value); }
        }




        /// <remarks/>
        // [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        [XmlIgnore]
        public System.DateTime Data_platnosci
        {
            get
            {
                return this.data_platnosciField;
            }
            set
            {
                this.data_platnosciField = value;
            }
        }


        [XmlElement("Data_platnosci")]
        public string XmlDateTimeDataPlatnosci
        {


            get
            {
                return Data_platnosci.ToString("yyyy-MM-dd");
            }
            set { Data_platnosci =  DateTime.Parse(value); }
        }
      
       


        /// <remarks/>
        public string Typ_obciazenia
        {
            get
            {
                return this.typ_obciazeniaField;
            }
            set
            {
                this.typ_obciazeniaField = value;
            }
        }

        public string Rodzaj_obciazenia
        {

            get
            {
                return this.rodzaj_obciazeniaField;
            }
            set
            {
                this.rodzaj_obciazeniaField = value;
            }
        }

        /// <remarks/>
        public string Okres_odsetkowy_od
        {
            get
            {
                return this.okres_odsetkowy_odField;
            }
            set
            {
                this.okres_odsetkowy_odField = value;
            }
        }

       
        /// <remarks/>
        public string Okres_odsetkowy_do
        {
            get
            {
                return this.okres_odsetkowy_doField;
            }
            set
            {
                this.okres_odsetkowy_doField = value;
            }
        }
        [XmlAttribute("TypOdsetek")]
        public typOdsetek TypOdsetek
        {
            get
            {
                return this.typOdsetekField;
            }
            set
            {
                this.typOdsetekField = value;
            }
        }
        [XmlIgnore]
        public typy_Odsetek? Typ_odsetek
        {
            get
            {
                return this.typ_OdsetekField;
            }
            set
            {
                this.typ_OdsetekField = value;
            }
        }

        [XmlElement("Typ_odsetek")]
        public string typy_OdsetekAsString
        {
            get
            {
                return (Typ_odsetek != null && ((int)Typ_odsetek) > 0) ? this.typ_OdsetekField.ToString(): typy_Odsetek.Brak.ToString();
            }
            set
            {
                if (string.IsNullOrWhiteSpace(value))
                {
                    Typ_odsetek = typy_Odsetek.Brak;
                }
                else
                {
                    Typ_odsetek  = (typy_Odsetek)Enum.Parse(typeof(typy_Odsetek), value,false);
                }
            }
        }

        /// <remarks/>
        public string Nr_faktury
        {
            get
            {
                return this.nr_fakturyField;
            }
            set
            {
                this.nr_fakturyField = value;
            }
        }

        [XmlIgnore]
        public decimal OZE
        {
            get
            {
                return this.ozeField;
            }
            set
            {
                this.ozeField = value;
            }
        }


        //[XmlAttribute("OZE")]
        [XmlElement("Kwota_oze")]
        public string ozeStr
        {

            get
            {
                return string.Format(CultureInfo.InvariantCulture, "{0:0.00}", OZE);
            }
            set
            {
                decimal result = 0;
                if (decimal.TryParse(value, NumberStyles.Number | NumberStyles.AllowDecimalPoint | NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out result))
                    OZE = result;
                else
                    OZE = 0;
            }
        }


        [XmlIgnore]
        public decimal Przejsciowa
        {
            get
            {
                return this.przejsciowaField;
            }
            set
            {
                this.przejsciowaField = value;
            }
        }


        //[XmlAttribute("Przejsciowa")]
        [XmlElement("Kwota_opl_przejsc")]
        public string przejsciowaStr
        {

            get
            {
                return string.Format(CultureInfo.InvariantCulture, "{0:0.00}", Przejsciowa);
            }
            set
            {
                decimal result = 0;
                if (decimal.TryParse(value, NumberStyles.Number | NumberStyles.AllowDecimalPoint | NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out result))
                    Przejsciowa = result;
                else
                    Przejsciowa = 0;
            }
        }


        [XmlIgnore]
        public decimal Kogeneracyjna
        {
            get
            {
                return this.kogeneracyjnaField;
            }
            set
            {
                this.kogeneracyjnaField = value;
            }
        }


        //[XmlAttribute("Kogeneracyjna")]
        [XmlElement("Kwota_opl_kogen")]
        public string kogeneracyjnaStr
        {

            get
            {
                return string.Format(CultureInfo.InvariantCulture, "{0:0.00}", Kogeneracyjna);
            }
            set
            {
                decimal result = 0;
                if (decimal.TryParse(value, NumberStyles.Number | NumberStyles.AllowDecimalPoint | NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out result))
                    Kogeneracyjna = result;
                else
                    Kogeneracyjna = 0;
            }
        }


        [XmlIgnore]
        public decimal Mocowa
        {
            get
            {
                return this.mocowaField;
            }
            set
            {
                this.mocowaField = value;
            }
        }


        //[XmlAttribute("Mocowa")]
        [XmlElement("Kwota_opl_mocowa")]
        public string mocowaStr
        {

            get
            {
                return string.Format(CultureInfo.InvariantCulture, "{0:0.00}", Mocowa);
            }
            set
            {
                decimal result = 0;
                if (decimal.TryParse(value, NumberStyles.Number | NumberStyles.AllowDecimalPoint | NumberStyles.AllowLeadingSign, CultureInfo.InvariantCulture, out result))
                    Mocowa = result;
                else
                    Mocowa = 0;
            }
        }

        [XmlIgnore]
        public System.DateTime Data_wys_KSEF
        {
            get
            {
                return this.data_wys_KSEFField;
            }
            set
            {
                this.data_wys_KSEFField = value;
            }
        }


        [XmlElement("Data_wys_KSEF")]
        public string XmlDateTimeData_wys_KSEF
        {


            get
            {
                return Data_wys_KSEF.ToString("yyyy-MM-dd");
            }
            set { Data_wys_KSEF = DateTime.Parse(value); }
        }

        [XmlIgnore]
        public System.DateTime? Data_prz_KSEF
        {
            get
            {
                return this.data_prz_KSEFField;
            }
            set
            {

                this.data_prz_KSEFField = value;
            }
        }


        [XmlElement("Data_prz_KSEF")]
        public string XmlDateTimeData_prz_KSEF
        {


            get
            {
                if (Data_prz_KSEF != null)
                    return Data_prz_KSEF.Value.ToString("yyyy-MM-dd");
                else
                    return null;
            }
            set
            {
                try
                {

                    Data_prz_KSEF= DateTime.Parse(value);
                }
                catch
                {
                    Data_prz_KSEF = null;
                }
                
            }
        }

        [XmlElement("Data_ksef")]
        public string XmlDateTimeData_prz_KSEF1
        {


            get
            {
                if (Data_prz_KSEF != null)
                    return Data_prz_KSEF.Value.ToString("yyyy-MM-dd");
                else
                    return null;

            }
            set {
                try
                {

                    Data_prz_KSEF = DateTime.Parse(value);
                }
                catch
                {
                    Data_prz_KSEF = null;
                }
            }
        }

        [XmlIgnore]
        public string Nr_KSEF
        {
            get { return this.nr_KSEFField; }
            set { }
        }
        [XmlElement("Nr_KSEF")]
        public string Nr_KSEF1
        {
            get
            {
                return this.nr_KSEFField;
            }
            set
            {
                this.nr_KSEFField = value;
            }
        }
        [XmlElement ("Nr_ksef")]
        public string NrKSEF2
        {
            get
            {
                return this.nr_KSEFField;
            }
            set
            {
                this.nr_KSEFField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Wplata", IsNullable = false)]
        public LexEnaTrs.Web.Models.Wplata[] Wplaty
        {
            get
            {
                return this.wplatyField;
            }
            set
            {
                this.wplatyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Doksiegowania
    {

        private Doksiegowanie doksiegowanieField;

        /// <remarks/>
        public Doksiegowanie Doksiegowanie
        {
            get
            {
                return this.doksiegowanieField;
            }
            set
            {
                this.doksiegowanieField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Doksiegowanie
    {

        private sbyte wartosc_doksiegowaniaField;

        private Typ_doksiegowania typ_doksiegowaniaField;

        /// <remarks/>
        public sbyte Wartosc_doksiegowania
        {
            get
            {
                return this.wartosc_doksiegowaniaField;
            }
            set
            {
                this.wartosc_doksiegowaniaField = value;
            }
        }

        /// <remarks/>
        public Typ_doksiegowania Typ_doksiegowania
        {
            get
            {
                return this.typ_doksiegowaniaField;
            }
            set
            {
                this.typ_doksiegowaniaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Odbiorcy
    {

        private Odbiorca[] odbiorcaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Odbiorca")]
        public Odbiorca[] Odbiorca
        {
            get
            {
                return this.odbiorcaField;
            }
            set
            {
                this.odbiorcaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Obciazenia
    {

        private Obciazenie[] obciazenieField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Obciazenie")]
        public Obciazenie[] Obciazenie
        {
            get
            {
                return this.obciazenieField;
            }
            set
            {
                this.obciazenieField = value;
            }
        }
    }
}