//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Linq;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System;
using System.Xml.Schema;
using System.IO;
using LexEnaTrs;
using System.ComponentModel.DataAnnotations;



// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace LexEnaTrs
{
    /// <remarks/>
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = Constants.currnamespace)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = Constants.currnamespace, IsNullable = false)]
    public partial class DokumentEPU : INotifyPropertyChanged
    {

        private int iDSprawyField;

        private int iDSprawyProEPUField;

        private string sygnaturaField;

        private int iDDoreczeniaField;

        private bool iDDoreczeniaFieldSpecified;

        private string pESELPelnomocnikaField;

        private System.DateTime dataZlozeniaField;

        private int rodzajField;

        private string przedmiotField;

        private typSkladajacy osobaSkladajacaField;

        private ObservableCollection<typStrona> listaPowodowField;

        private ObservableCollection<typStrona> listaPozwanychField;

        private string trescField;
        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged(PropertyChangedEventArgs args)
        {
            PropertyChangedEventHandler handler = this.PropertyChanged;
            if (handler != null)
            {
                handler(this, args);
            }
        }
        private void OnPropertyChanged(string propertyName)
        {
            this.OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }

         [System.Xml.Serialization.XmlIgnoreAttribute()]
        public int IDSprawyProEPU
        {
            get
            {
                return this.iDSprawyProEPUField;
            }
            set
            {
                if (value != this.iDSprawyProEPUField)
                {
                    this.iDSprawyProEPUField = value;
                    this.OnPropertyChanged("IDSprawyProEPU");
                }
            }

        }

        /// <remarks/>
        public int IDSprawy
        {
            get
            {
                return this.iDSprawyField;
            }
            set
            {
                if (value != this.iDSprawyField)
                {
                this.iDSprawyField = value;
                this.OnPropertyChanged("IDSprawy");
                }
            }

        }

        /// <remarks/>
        public string Sygnatura
        {
            get
            {
                return this.sygnaturaField;
            }
            set
            {

                if (value != this.sygnaturaField)
                {
                    this.sygnaturaField = value;
                    this.OnPropertyChanged("Sygnatura");
                }
                
            }
        }

        /// <remarks/>
        public int IDDoreczenia
        {
            get
            {
                return this.iDDoreczeniaField;
            }
            set
            {
             
                if (value != this.iDDoreczeniaField)
                {
                    this.iDDoreczeniaField = value;
                    this.OnPropertyChanged("IDDoreczenia");
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDDoreczeniaSpecified
        {
            get
            {
                return this.iDDoreczeniaFieldSpecified;
            }
            set
            {
                this.iDDoreczeniaFieldSpecified = value;
            }
        }

        /// <remarks/>
        public string PESELPelnomocnika
        {
            get
            {
                return this.pESELPelnomocnikaField;
            }
            set
            {
              
                if (value != this.pESELPelnomocnikaField)
                {
                    this.pESELPelnomocnikaField = value;
                    this.OnPropertyChanged("PESELPelnomocnika");
                }
            }
        }

        /// <remarks/>
        public System.DateTime DataZlozenia
        {
            get
            {
                return this.dataZlozeniaField;
            }
            set
            {
               if (value != this.dataZlozeniaField)
                {
                    this.dataZlozeniaField = value;
                    this.OnPropertyChanged("DataZlozenia");
                }
            }
        }

        /// <remarks/>
        public int Rodzaj
        {
            get
            {
                return this.rodzajField;
            }
            set
            {
     
                if (value != this.rodzajField)
                {
                    this.rodzajField = value;
                    this.OnPropertyChanged("Rodzaj");
                }
            }
        }

        /// <remarks/>
        public string Przedmiot
        {
            get
            {
                return this.przedmiotField;
            }
            set
            {

                if (value != this.przedmiotField)
                {
                    this.przedmiotField = value;
                    this.OnPropertyChanged("Rodzaj");
                }
            }
        }

        /// <remarks/>
        public typSkladajacy OsobaSkladajaca
        {
            get
            {
                return this.osobaSkladajacaField;
            }
            set
            {
               if (value != this.osobaSkladajacaField)
                {
                    this.osobaSkladajacaField = value;
                    this.OnPropertyChanged("Rodzaj");
                }
            }
        }

        /// <remarks/>
      
        [System.Xml.Serialization.XmlArrayItemAttribute("Powod", IsNullable = false)]
        public ObservableCollection<typStrona> ListaPowodow
        {
            get
            {
                return this.listaPowodowField;
            }
            set
            {

                if (value != this.listaPowodowField)
                {
                    this.listaPowodowField = value;
                    this.OnPropertyChanged("ListaPowodow");
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("Pozwany", IsNullable = true)]
        public ObservableCollection<typStrona> ListaPozwanych
        {
            get
            {
                return this.listaPozwanychField;
            }
            set
            {


                if (value != this.listaPozwanychField)
                {
                    this.listaPozwanychField = value;
                    this.OnPropertyChanged("ListaPozwanych");
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Tresc
        {
            get
            {
                return this.trescField;
            }
            set
            {
                this.trescField = value;

                if (value != this.trescField)
                {
                    this.trescField = value;
                    this.OnPropertyChanged("Tresc");
                }
            }
        }
    }
}