//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.currenda.pl/epu")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.currenda.pl/epu", IsNullable=false)]
public partial class Types {
    
    private typRodzajCzynnosci alaField;
    
    /// <remarks/>
    public typRodzajCzynnosci ala {
        get {
            return this.alaField;
        }
        set {
            this.alaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public enum typRodzajCzynnosci {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("podjęcie postępowania egzekucyjnego")]
    podjęciepostępowaniaegzekucyjnego,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("koszty egzekucyjne poniesione przez wierzyciela")]
    kosztyegzekucyjneponiesioneprzezwierzyciela,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("umorzono przez wyegzekwowanie w całości")]
    umorzonoprzezwyegzekwowaniewcałości,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("umorzono przez wyegzekwowanie w części")]
    umorzonoprzezwyegzekwowaniewczęści,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("umorzono w inny sposób")]
    umorzonowinnysposób,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("zwrot wniosku")]
    zwrotwniosku,
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("przekazano sprawę")]
    przekazanosprawę,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typInnyRejestr {
    
    private string typField;
    
    private string organField;
    
    private string numerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string typ {
        get {
            return this.typField;
        }
        set {
            this.typField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string organ {
        get {
            return this.organField;
        }
        set {
            this.organField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numer {
        get {
            return this.numerField;
        }
        set {
            this.numerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typInstytucja {
    
    private string nazwaField;
    
    private string siedzibaField;
    
    private string rEGONField;
    
    private sbyte czyRejestrField;
    
    private object itemField;
    
    private typOsoba[] listaZarzaduField;
    
    /// <remarks/>
    public string Nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
    
    /// <remarks/>
    public string Siedziba {
        get {
            return this.siedzibaField;
        }
        set {
            this.siedzibaField = value;
        }
    }
    
    /// <remarks/>
    public string REGON {
        get {
            return this.rEGONField;
        }
        set {
            this.rEGONField = value;
        }
    }
    
    /// <remarks/>
    public sbyte czyRejestr {
        get {
            return this.czyRejestrField;
        }
        set {
            this.czyRejestrField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InnyRejestr", typeof(typInnyRejestr))]
    [System.Xml.Serialization.XmlElementAttribute("KRS", typeof(string))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("CzlonekZarzadu", IsNullable=false)]
    public typOsoba[] ListaZarzadu {
        get {
            return this.listaZarzaduField;
        }
        set {
            this.listaZarzaduField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typOsoba {
    
    private string imieField;
    
    private string imie2Field;
    
    private string nazwiskoField;
    
    private string pESELField;
    
    private string stanowiskoField;
    
    /// <remarks/>
    public string Imie {
        get {
            return this.imieField;
        }
        set {
            this.imieField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Imie2 {
        get {
            return this.imie2Field;
        }
        set {
            this.imie2Field = value;
        }
    }
    
    /// <remarks/>
    public string Nazwisko {
        get {
            return this.nazwiskoField;
        }
        set {
            this.nazwiskoField = value;
        }
    }
    
    /// <remarks/>
    public string PESEL {
        get {
            return this.pESELField;
        }
        set {
            this.pESELField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string stanowisko {
        get {
            return this.stanowiskoField;
        }
        set {
            this.stanowiskoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typOsobaFizyczna {
    
    private string imieField;
    
    private string imie2Field;
    
    private string nazwiskoField;
    
    private string nazwaField;
    
    private string pESELField;
    
    private string nrDokumentuField;
    
    private string imieOjcaField;
    
    private string imieMatkiField;
    
    private string nazwiskoRodoweField;
    
    private string nazwiskoRodoweMatkiField;
    
    private string miejsceUrodzeniaField;
    
    private string dataUrodzeniaField;
    
    /// <remarks/>
    public string Imie {
        get {
            return this.imieField;
        }
        set {
            this.imieField = value;
        }
    }
    
    /// <remarks/>
    public string Imie2 {
        get {
            return this.imie2Field;
        }
        set {
            this.imie2Field = value;
        }
    }
    
    /// <remarks/>
    public string Nazwisko {
        get {
            return this.nazwiskoField;
        }
        set {
            this.nazwiskoField = value;
        }
    }
    
    /// <remarks/>
    public string Nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
    
    /// <remarks/>
    public string PESEL {
        get {
            return this.pESELField;
        }
        set {
            this.pESELField = value;
        }
    }
    
    /// <remarks/>
    public string NrDokumentu {
        get {
            return this.nrDokumentuField;
        }
        set {
            this.nrDokumentuField = value;
        }
    }
    
    /// <remarks/>
    public string ImieOjca {
        get {
            return this.imieOjcaField;
        }
        set {
            this.imieOjcaField = value;
        }
    }
    
    /// <remarks/>
    public string ImieMatki {
        get {
            return this.imieMatkiField;
        }
        set {
            this.imieMatkiField = value;
        }
    }
    
    /// <remarks/>
    public string NazwiskoRodowe {
        get {
            return this.nazwiskoRodoweField;
        }
        set {
            this.nazwiskoRodoweField = value;
        }
    }
    
    /// <remarks/>
    public string NazwiskoRodoweMatki {
        get {
            return this.nazwiskoRodoweMatkiField;
        }
        set {
            this.nazwiskoRodoweMatkiField = value;
        }
    }
    
    /// <remarks/>
    public string MiejsceUrodzenia {
        get {
            return this.miejsceUrodzeniaField;
        }
        set {
            this.miejsceUrodzeniaField = value;
        }
    }
    
    /// <remarks/>
    public string DataUrodzenia {
        get {
            return this.dataUrodzeniaField;
        }
        set {
            this.dataUrodzeniaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typStrona {
    
    private sbyte reprezentacjaField;
    
    private sbyte rodzajStronyField;
    
    private object itemField;
    
    private string nIPField;
    
    private typAdres[] adresField;
    
    private ulong idField;
    
    public typStrona() {
        this.reprezentacjaField = ((sbyte)(1));
    }
    
    /// <remarks/>
    public sbyte reprezentacja {
        get {
            return this.reprezentacjaField;
        }
        set {
            this.reprezentacjaField = value;
        }
    }
    
    /// <remarks/>
    public sbyte rodzajStrony {
        get {
            return this.rodzajStronyField;
        }
        set {
            this.rodzajStronyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Instytucja", typeof(typInstytucja))]
    [System.Xml.Serialization.XmlElementAttribute("OsobaFizyczna", typeof(typOsobaFizyczna))]
    public object Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    public string NIP {
        get {
            return this.nIPField;
        }
        set {
            this.nIPField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Adres")]
    public typAdres[] Adres {
        get {
            return this.adresField;
        }
        set {
            this.adresField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typAdres {
    
    private string ulicaField;
    
    private string nr_domuField;
    
    private string nr_mieszkaniaField;
    
    private string kodField;
    
    private string miejscowoscField;
    
    private string pocztaField;
    
    private string krajField;
    
    private string wojewodztwoField;
    
    private string powiatField;
    
    private string gminaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ulica {
        get {
            return this.ulicaField;
        }
        set {
            this.ulicaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nr_domu {
        get {
            return this.nr_domuField;
        }
        set {
            this.nr_domuField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nr_mieszkania {
        get {
            return this.nr_mieszkaniaField;
        }
        set {
            this.nr_mieszkaniaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kod {
        get {
            return this.kodField;
        }
        set {
            this.kodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string miejscowosc {
        get {
            return this.miejscowoscField;
        }
        set {
            this.miejscowoscField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string poczta {
        get {
            return this.pocztaField;
        }
        set {
            this.pocztaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string kraj {
        get {
            return this.krajField;
        }
        set {
            this.krajField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string wojewodztwo {
        get {
            return this.wojewodztwoField;
        }
        set {
            this.wojewodztwoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string powiat {
        get {
            return this.powiatField;
        }
        set {
            this.powiatField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string gmina {
        get {
            return this.gminaField;
        }
        set {
            this.gminaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typSkladajacy {
    
    private typOsoba osobaField;
    
    private string nazwaField;
    
    private typAdres adresField;
    
    private sbyte pelnomocnikField;
    
    private string podstawaField;
    
    /// <remarks/>
    public typOsoba Osoba {
        get {
            return this.osobaField;
        }
        set {
            this.osobaField = value;
        }
    }
    
    /// <remarks/>
    public string Nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
    
    /// <remarks/>
    public typAdres Adres {
        get {
            return this.adresField;
        }
        set {
            this.adresField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte pelnomocnik {
        get {
            return this.pelnomocnikField;
        }
        set {
            this.pelnomocnikField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string podstawa {
        get {
            return this.podstawaField;
        }
        set {
            this.podstawaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typOrzeczenie {
    
    private ulong iDOrzeczeniaField;
    
    private string sygnaturaField;
    
    private sbyte kodDecyzjiField;
    
    private System.DateTime dataOrzeczeniaField;
    
    private string opisField;
    
    /// <remarks/>
    public ulong IDOrzeczenia {
        get {
            return this.iDOrzeczeniaField;
        }
        set {
            this.iDOrzeczeniaField = value;
        }
    }
    
    /// <remarks/>
    public string Sygnatura {
        get {
            return this.sygnaturaField;
        }
        set {
            this.sygnaturaField = value;
        }
    }
    
    /// <remarks/>
    public sbyte KodDecyzji {
        get {
            return this.kodDecyzjiField;
        }
        set {
            this.kodDecyzjiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DataOrzeczenia {
        get {
            return this.dataOrzeczeniaField;
        }
        set {
            this.dataOrzeczeniaField = value;
        }
    }
    
    /// <remarks/>
    public string Opis {
        get {
            return this.opisField;
        }
        set {
            this.opisField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.currenda.pl/epu", IsNullable=false)]
public partial class ZazalenieEPU {
    
    private typOrzeczenie orzeczenieField;
    
    private System.DateTime dataZazaleniaField;
    
    private typSkladajacy osobaSkladajacaField;
    
    private typStrona[] listaPowodowField;
    
    private typStrona[] listaPozwanychField;
    
    private string trescField;
    
    /// <remarks/>
    public typOrzeczenie Orzeczenie {
        get {
            return this.orzeczenieField;
        }
        set {
            this.orzeczenieField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DataZazalenia {
        get {
            return this.dataZazaleniaField;
        }
        set {
            this.dataZazaleniaField = value;
        }
    }
    
    /// <remarks/>
    public typSkladajacy OsobaSkladajaca {
        get {
            return this.osobaSkladajacaField;
        }
        set {
            this.osobaSkladajacaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Powod", IsNullable=false)]
    public typStrona[] ListaPowodow {
        get {
            return this.listaPowodowField;
        }
        set {
            this.listaPowodowField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Pozwany", IsNullable=false)]
    public typStrona[] ListaPozwanych {
        get {
            return this.listaPozwanychField;
        }
        set {
            this.listaPozwanychField = value;
        }
    }
    
    /// <remarks/>
    public string Tresc {
        get {
            return this.trescField;
        }
        set {
            this.trescField = value;
        }
    }
}
