//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexEna2BIG.KRDSiddinService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", ConfigurationName="KRDSiddinService.Import")]
    public interface Import {
        
        // CODEGEN: Generating message contract since the operation Login is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.LoginResponse1 Login(LexEna2BIG.KRDSiddinService.LoginRequest1 request);
        
        // CODEGEN: Generating message contract since the operation LoginEx is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/LoginEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.LoginExResponse LoginEx(LexEna2BIG.KRDSiddinService.LoginExRequest1 request);
        
        // CODEGEN: Generating message contract since the operation Logout is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/Logout", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.LogoutResponse Logout(LexEna2BIG.KRDSiddinService.LogoutRequest1 request);
        
        // CODEGEN: Generating message contract since the operation UploadChunk is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/UploadChunk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.UploadChunkResponse UploadChunk(LexEna2BIG.KRDSiddinService.UploadChunkRequest request);
        
        // CODEGEN: Generating message contract since the operation CloseChunkBag is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/CloseChunkBag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.CloseChunkBagResponse CloseChunkBag(LexEna2BIG.KRDSiddinService.CloseChunkBagRequest1 request);
        
        // CODEGEN: Generating message contract since the operation CloseChunkBagEx is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/CloseChunkBagEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.CloseChunkBagExResponse CloseChunkBagEx(LexEna2BIG.KRDSiddinService.CloseChunkBagExRequest request);
        
        // CODEGEN: Generating message contract since the operation GetChunkBag is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/GetChunkBag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.GetChunkBagResponse GetChunkBag(LexEna2BIG.KRDSiddinService.GetChunkBagRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetChunkBagEx is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/GetChunkBagEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.GetChunkBagExResponse GetChunkBagEx(LexEna2BIG.KRDSiddinService.GetChunkBagExRequest request);
        
        // CODEGEN: Generating message contract since the operation GetRepeatFile is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/GetRepeatFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.GetRepeatFileResponse GetRepeatFile(LexEna2BIG.KRDSiddinService.GetRepeatFileRequest1 request);
        
        // CODEGEN: Generating message contract since the operation DownloadChunk is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/DownloadChunk", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.DownloadChunkResponse DownloadChunk(LexEna2BIG.KRDSiddinService.DownloadChunkRequest1 request);
        
        // CODEGEN: Generating message contract since the operation GetJobs is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/GetJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.GetJobsResponse GetJobs(LexEna2BIG.KRDSiddinService.GetJobsRequest1 request);
        
        // CODEGEN: Generating message contract since the operation CancelJob is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/CancelJob", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.CancelJobResponse CancelJob(LexEna2BIG.KRDSiddinService.CancelJobRequest1 request);
        
        // CODEGEN: Generating message contract since the operation RemoveChunkBag is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://Siddin.ServiceContracts/2006/09/RemoveChunkBag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignedRequest))]
        LexEna2BIG.KRDSiddinService.RemoveChunkBagResponse RemoveChunkBag(LexEna2BIG.KRDSiddinService.RemoveChunkBagRequest1 request);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LoginExRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class LoginRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.DataTypes/2006/09")]
    public partial class Job : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int jobNumberField;
        
        private int queueNumberField;
        
        private System.DateTime queueDateField;
        
        private string statusField;
        
        private JobStatusCodeEnum statusCodeField;
        
        private int progressField;
        
        private string queueLoginField;
        
        private System.Guid jobIDField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int JobNumber {
            get {
                return this.jobNumberField;
            }
            set {
                this.jobNumberField = value;
                this.RaisePropertyChanged("JobNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int QueueNumber {
            get {
                return this.queueNumberField;
            }
            set {
                this.queueNumberField = value;
                this.RaisePropertyChanged("QueueNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime QueueDate {
            get {
                return this.queueDateField;
            }
            set {
                this.queueDateField = value;
                this.RaisePropertyChanged("QueueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public JobStatusCodeEnum StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Progress {
            get {
                return this.progressField;
            }
            set {
                this.progressField = value;
                this.RaisePropertyChanged("Progress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string QueueLogin {
            get {
                return this.queueLoginField;
            }
            set {
                this.queueLoginField = value;
                this.RaisePropertyChanged("QueueLogin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.Guid JobID {
            get {
                return this.jobIDField;
            }
            set {
                this.jobIDField = value;
                this.RaisePropertyChanged("JobID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.DataTypes/2006/09")]
    public enum JobStatusCodeEnum {
        
        /// <remarks/>
        CANCELED,
        
        /// <remarks/>
        FAILED,
        
        /// <remarks/>
        PROCESSED,
        
        /// <remarks/>
        QUEUED,
        
        /// <remarks/>
        STARTED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class ParameterType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private KeyEnum keyField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public KeyEnum Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public enum KeyEnum {
        
        /// <remarks/>
        CsvSeparator,
        
        /// <remarks/>
        CsvStartLine,
        
        /// <remarks/>
        CsvStartColumn,
        
        /// <remarks/>
        CsvAdditionalColumnCount,
        
        /// <remarks/>
        CsvGetCasesResponseOperation,
        
        /// <remarks/>
        CsvGetCasesResponseOperationExtension,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.DataTypes/2006/09")]
    public partial class ChunkBagEx : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private int countField;
        
        private long sizeField;
        
        private ProtocolVersionEnum protocolVersionField;
        
        private ProtocolEnum protocolTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ProtocolVersionEnum ProtocolVersion {
            get {
                return this.protocolVersionField;
            }
            set {
                this.protocolVersionField = value;
                this.RaisePropertyChanged("ProtocolVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ProtocolEnum ProtocolType {
            get {
                return this.protocolTypeField;
            }
            set {
                this.protocolTypeField = value;
                this.RaisePropertyChanged("ProtocolType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.DataTypes/2006/09")]
    public enum ProtocolVersionEnum {
        
        /// <remarks/>
        NotSpecified,
        
        /// <remarks/>
        Version_1_1,
        
        /// <remarks/>
        Version_1_2,
        
        /// <remarks/>
        Version_2_0,
        
        /// <remarks/>
        Version_2_1,
        
        /// <remarks/>
        Version_3_0,
        
        /// <remarks/>
        Version_1_0,
        
        /// <remarks/>
        Version_3_1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.DataTypes/2006/09")]
    public enum ProtocolEnum {
        
        /// <remarks/>
        NotSpecified,
        
        /// <remarks/>
        Nicci,
        
        /// <remarks/>
        Kip,
        
        /// <remarks/>
        Neal,
        
        /// <remarks/>
        Tovi,
        
        /// <remarks/>
        Najari,
        
        /// <remarks/>
        Veta,
        
        /// <remarks/>
        Pasha,
        
        /// <remarks/>
        Violet,
        
        /// <remarks/>
        Warren,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.DataTypes/2006/09")]
    public partial class ChunkBag : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private int countField;
        
        private long sizeField;
        
        private NicciVersionEnum nicciVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public NicciVersionEnum NicciVersion {
            get {
                return this.nicciVersionField;
            }
            set {
                this.nicciVersionField = value;
                this.RaisePropertyChanged("NicciVersion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.DataTypes/2006/09")]
    public enum NicciVersionEnum {
        
        /// <remarks/>
        NotSpecified,
        
        /// <remarks/>
        Version_1_1,
        
        /// <remarks/>
        Version_1_2,
        
        /// <remarks/>
        Version_2_0,
        
        /// <remarks/>
        Version_2_1,
        
        /// <remarks/>
        Version_3_0,
        
        /// <remarks/>
        Version_3_1,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RemoveChunkBagRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CancelJobRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetJobsRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DownloadChunkRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetRepeatFileRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetChunkBagRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetChunkBagRequestEx))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CloseChunkBagRequestEx))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CloseChunkBagRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UpladChunkRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LogoutRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class SignedRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ticketField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("Ticket");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class RemoveChunkBagRequest : SignedRequest {
        
        private System.Guid chunkBagIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ChunkBagId {
            get {
                return this.chunkBagIdField;
            }
            set {
                this.chunkBagIdField = value;
                this.RaisePropertyChanged("ChunkBagId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class CancelJobRequest : SignedRequest {
        
        private System.Guid jobIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
                this.RaisePropertyChanged("JobId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class GetJobsRequest : SignedRequest {
        
        private bool getAllField;
        
        private System.DateTime lastGetField;
        
        private int lastNumberField;
        
        private bool lastNumberFieldSpecified;
        
        private System.Guid jobIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool GetAll {
            get {
                return this.getAllField;
            }
            set {
                this.getAllField = value;
                this.RaisePropertyChanged("GetAll");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime LastGet {
            get {
                return this.lastGetField;
            }
            set {
                this.lastGetField = value;
                this.RaisePropertyChanged("LastGet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int LastNumber {
            get {
                return this.lastNumberField;
            }
            set {
                this.lastNumberField = value;
                this.RaisePropertyChanged("LastNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LastNumberSpecified {
            get {
                return this.lastNumberFieldSpecified;
            }
            set {
                this.lastNumberFieldSpecified = value;
                this.RaisePropertyChanged("LastNumberSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Guid JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
                this.RaisePropertyChanged("JobId");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class DownloadChunkRequest : SignedRequest {
        
        private ChunkBag chunkBagField;
        
        private int numberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ChunkBag ChunkBag {
            get {
                return this.chunkBagField;
            }
            set {
                this.chunkBagField = value;
                this.RaisePropertyChanged("ChunkBag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class GetRepeatFileRequest : SignedRequest {
        
        private System.Guid jobIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
                this.RaisePropertyChanged("JobId");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetChunkBagRequestEx))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class GetChunkBagRequest : SignedRequest {
        
        private System.Guid jobIdField;
        
        private int chunkSizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid JobId {
            get {
                return this.jobIdField;
            }
            set {
                this.jobIdField = value;
                this.RaisePropertyChanged("JobId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ChunkSize {
            get {
                return this.chunkSizeField;
            }
            set {
                this.chunkSizeField = value;
                this.RaisePropertyChanged("ChunkSize");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class GetChunkBagRequestEx : GetChunkBagRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class CloseChunkBagRequestEx : SignedRequest {
        
        private ChunkBagEx chunkBagExField;
        
        private string descriptionField;
        
        private bool getDifferenceField;
        
        private bool executeDifferenceField;
        
        private ParameterType[] parametersField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ChunkBagEx ChunkBagEx {
            get {
                return this.chunkBagExField;
            }
            set {
                this.chunkBagExField = value;
                this.RaisePropertyChanged("ChunkBagEx");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool GetDifference {
            get {
                return this.getDifferenceField;
            }
            set {
                this.getDifferenceField = value;
                this.RaisePropertyChanged("GetDifference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ExecuteDifference {
            get {
                return this.executeDifferenceField;
            }
            set {
                this.executeDifferenceField = value;
                this.RaisePropertyChanged("ExecuteDifference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Parameter", IsNullable=false)]
        public ParameterType[] Parameters {
            get {
                return this.parametersField;
            }
            set {
                this.parametersField = value;
                this.RaisePropertyChanged("Parameters");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class CloseChunkBagRequest : SignedRequest {
        
        private ChunkBag chunkBagField;
        
        private string descriptionField;
        
        private bool getDifferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ChunkBag ChunkBag {
            get {
                return this.chunkBagField;
            }
            set {
                this.chunkBagField = value;
                this.RaisePropertyChanged("ChunkBag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool GetDifference {
            get {
                return this.getDifferenceField;
            }
            set {
                this.getDifferenceField = value;
                this.RaisePropertyChanged("GetDifference");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class UpladChunkRequest : SignedRequest {
        
        private ChunkBag chunkBagField;
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ChunkBag ChunkBag {
            get {
                return this.chunkBagField;
            }
            set {
                this.chunkBagField = value;
                this.RaisePropertyChanged("ChunkBag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class LogoutRequest : SignedRequest {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class LoginResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ticketField;
        
        private string fullNameField;
        
        private bool mustChangePasswordField;
        
        private int passwordExpireDaysCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ticket {
            get {
                return this.ticketField;
            }
            set {
                this.ticketField = value;
                this.RaisePropertyChanged("Ticket");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FullName {
            get {
                return this.fullNameField;
            }
            set {
                this.fullNameField = value;
                this.RaisePropertyChanged("FullName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool MustChangePassword {
            get {
                return this.mustChangePasswordField;
            }
            set {
                this.mustChangePasswordField = value;
                this.RaisePropertyChanged("MustChangePassword");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int PasswordExpireDaysCount {
            get {
                return this.passwordExpireDaysCountField;
            }
            set {
                this.passwordExpireDaysCountField = value;
                this.RaisePropertyChanged("PasswordExpireDaysCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://Siddin.ServiceContracts/2006/09")]
    public partial class LoginExRequest : LoginRequest {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.LoginRequest LoginRequest;
        
        public LoginRequest1() {
        }
        
        public LoginRequest1(LexEna2BIG.KRDSiddinService.LoginRequest LoginRequest) {
            this.LoginRequest = LoginRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public string LoginResult;
        
        public LoginResponse1() {
        }
        
        public LoginResponse1(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginExRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.LoginExRequest LoginExRequest;
        
        public LoginExRequest1() {
        }
        
        public LoginExRequest1(LexEna2BIG.KRDSiddinService.LoginExRequest LoginExRequest) {
            this.LoginExRequest = LoginExRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.LoginResponse LoginResponse;
        
        public LoginExResponse() {
        }
        
        public LoginExResponse(LexEna2BIG.KRDSiddinService.LoginResponse LoginResponse) {
            this.LoginResponse = LoginResponse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.LogoutRequest LogoutRequest;
        
        public LogoutRequest1() {
        }
        
        public LogoutRequest1(LexEna2BIG.KRDSiddinService.LogoutRequest LogoutRequest) {
            this.LogoutRequest = LogoutRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogoutResponse {
        
        public LogoutResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadChunkRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.UpladChunkRequest UpladChunkBagRequest;
        
        public UploadChunkRequest() {
        }
        
        public UploadChunkRequest(LexEna2BIG.KRDSiddinService.UpladChunkRequest UpladChunkBagRequest) {
            this.UpladChunkBagRequest = UpladChunkBagRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadChunkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.DataTypes/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.ChunkBag UploadChunkResult;
        
        public UploadChunkResponse() {
        }
        
        public UploadChunkResponse(LexEna2BIG.KRDSiddinService.ChunkBag UploadChunkResult) {
            this.UploadChunkResult = UploadChunkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloseChunkBagRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.CloseChunkBagRequest CloseChunkRequest;
        
        public CloseChunkBagRequest1() {
        }
        
        public CloseChunkBagRequest1(LexEna2BIG.KRDSiddinService.CloseChunkBagRequest CloseChunkRequest) {
            this.CloseChunkRequest = CloseChunkRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloseChunkBagResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public System.Guid CloseChunkBagResult;
        
        public CloseChunkBagResponse() {
        }
        
        public CloseChunkBagResponse(System.Guid CloseChunkBagResult) {
            this.CloseChunkBagResult = CloseChunkBagResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloseChunkBagExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.CloseChunkBagRequestEx CloseChunkRequestEx;
        
        public CloseChunkBagExRequest() {
        }
        
        public CloseChunkBagExRequest(LexEna2BIG.KRDSiddinService.CloseChunkBagRequestEx CloseChunkRequestEx) {
            this.CloseChunkRequestEx = CloseChunkRequestEx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CloseChunkBagExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public System.Guid CloseChunkBagExResult;
        
        public CloseChunkBagExResponse() {
        }
        
        public CloseChunkBagExResponse(System.Guid CloseChunkBagExResult) {
            this.CloseChunkBagExResult = CloseChunkBagExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChunkBagRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.GetChunkBagRequest GetChunkBagRequest;
        
        public GetChunkBagRequest1() {
        }
        
        public GetChunkBagRequest1(LexEna2BIG.KRDSiddinService.GetChunkBagRequest GetChunkBagRequest) {
            this.GetChunkBagRequest = GetChunkBagRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChunkBagResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.DataTypes/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.ChunkBag GetChunkBagResult;
        
        public GetChunkBagResponse() {
        }
        
        public GetChunkBagResponse(LexEna2BIG.KRDSiddinService.ChunkBag GetChunkBagResult) {
            this.GetChunkBagResult = GetChunkBagResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChunkBagExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.GetChunkBagRequestEx GetChunkBagRequestEx;
        
        public GetChunkBagExRequest() {
        }
        
        public GetChunkBagExRequest(LexEna2BIG.KRDSiddinService.GetChunkBagRequestEx GetChunkBagRequestEx) {
            this.GetChunkBagRequestEx = GetChunkBagRequestEx;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetChunkBagExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.DataTypes/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.ChunkBagEx GetChunkBagExResult;
        
        public GetChunkBagExResponse() {
        }
        
        public GetChunkBagExResponse(LexEna2BIG.KRDSiddinService.ChunkBagEx GetChunkBagExResult) {
            this.GetChunkBagExResult = GetChunkBagExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRepeatFileRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.GetRepeatFileRequest GetRepeatFileRequest;
        
        public GetRepeatFileRequest1() {
        }
        
        public GetRepeatFileRequest1(LexEna2BIG.KRDSiddinService.GetRepeatFileRequest GetRepeatFileRequest) {
            this.GetRepeatFileRequest = GetRepeatFileRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRepeatFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public string GetRepeatFileResult;
        
        public GetRepeatFileResponse() {
        }
        
        public GetRepeatFileResponse(string GetRepeatFileResult) {
            this.GetRepeatFileResult = GetRepeatFileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadChunkRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.DownloadChunkRequest DownloadChunkRequest;
        
        public DownloadChunkRequest1() {
        }
        
        public DownloadChunkRequest1(LexEna2BIG.KRDSiddinService.DownloadChunkRequest DownloadChunkRequest) {
            this.DownloadChunkRequest = DownloadChunkRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DownloadChunkResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public string DownloadChunkResult;
        
        public DownloadChunkResponse() {
        }
        
        public DownloadChunkResponse(string DownloadChunkResult) {
            this.DownloadChunkResult = DownloadChunkResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJobsRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.GetJobsRequest GetJobsRequest;
        
        public GetJobsRequest1() {
        }
        
        public GetJobsRequest1(LexEna2BIG.KRDSiddinService.GetJobsRequest GetJobsRequest) {
            this.GetJobsRequest = GetJobsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetJobsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.Job[] GetJobsResult;
        
        public GetJobsResponse() {
        }
        
        public GetJobsResponse(LexEna2BIG.KRDSiddinService.Job[] GetJobsResult) {
            this.GetJobsResult = GetJobsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelJobRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.CancelJobRequest CancelJobRequest;
        
        public CancelJobRequest1() {
        }
        
        public CancelJobRequest1(LexEna2BIG.KRDSiddinService.CancelJobRequest CancelJobRequest) {
            this.CancelJobRequest = CancelJobRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelJobResponse {
        
        public CancelJobResponse() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveChunkBagRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Siddin.ServiceContracts/2006/09", Order=0)]
        public LexEna2BIG.KRDSiddinService.RemoveChunkBagRequest RemoveChunkBagRequest;
        
        public RemoveChunkBagRequest1() {
        }
        
        public RemoveChunkBagRequest1(LexEna2BIG.KRDSiddinService.RemoveChunkBagRequest RemoveChunkBagRequest) {
            this.RemoveChunkBagRequest = RemoveChunkBagRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveChunkBagResponse {
        
        public RemoveChunkBagResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImportChannel : LexEna2BIG.KRDSiddinService.Import, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImportClient : System.ServiceModel.ClientBase<LexEna2BIG.KRDSiddinService.Import>, LexEna2BIG.KRDSiddinService.Import {
        
        public ImportClient() {
        }
        
        public ImportClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImportClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImportClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.LoginResponse1 LexEna2BIG.KRDSiddinService.Import.Login(LexEna2BIG.KRDSiddinService.LoginRequest1 request) {
            return base.Channel.Login(request);
        }
        
        public string Login(LexEna2BIG.KRDSiddinService.LoginRequest LoginRequest) {
            LexEna2BIG.KRDSiddinService.LoginRequest1 inValue = new LexEna2BIG.KRDSiddinService.LoginRequest1();
            inValue.LoginRequest = LoginRequest;
            LexEna2BIG.KRDSiddinService.LoginResponse1 retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).Login(inValue);
            return retVal.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.LoginExResponse LexEna2BIG.KRDSiddinService.Import.LoginEx(LexEna2BIG.KRDSiddinService.LoginExRequest1 request) {
            return base.Channel.LoginEx(request);
        }
        
        public LexEna2BIG.KRDSiddinService.LoginResponse LoginEx(LexEna2BIG.KRDSiddinService.LoginExRequest LoginExRequest) {
            LexEna2BIG.KRDSiddinService.LoginExRequest1 inValue = new LexEna2BIG.KRDSiddinService.LoginExRequest1();
            inValue.LoginExRequest = LoginExRequest;
            LexEna2BIG.KRDSiddinService.LoginExResponse retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).LoginEx(inValue);
            return retVal.LoginResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.LogoutResponse LexEna2BIG.KRDSiddinService.Import.Logout(LexEna2BIG.KRDSiddinService.LogoutRequest1 request) {
            return base.Channel.Logout(request);
        }
        
        public void Logout(LexEna2BIG.KRDSiddinService.LogoutRequest LogoutRequest) {
            LexEna2BIG.KRDSiddinService.LogoutRequest1 inValue = new LexEna2BIG.KRDSiddinService.LogoutRequest1();
            inValue.LogoutRequest = LogoutRequest;
            LexEna2BIG.KRDSiddinService.LogoutResponse retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).Logout(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.UploadChunkResponse LexEna2BIG.KRDSiddinService.Import.UploadChunk(LexEna2BIG.KRDSiddinService.UploadChunkRequest request) {
            return base.Channel.UploadChunk(request);
        }
        
        public LexEna2BIG.KRDSiddinService.ChunkBag UploadChunk(LexEna2BIG.KRDSiddinService.UpladChunkRequest UpladChunkBagRequest) {
            LexEna2BIG.KRDSiddinService.UploadChunkRequest inValue = new LexEna2BIG.KRDSiddinService.UploadChunkRequest();
            inValue.UpladChunkBagRequest = UpladChunkBagRequest;
            LexEna2BIG.KRDSiddinService.UploadChunkResponse retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).UploadChunk(inValue);
            return retVal.UploadChunkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.CloseChunkBagResponse LexEna2BIG.KRDSiddinService.Import.CloseChunkBag(LexEna2BIG.KRDSiddinService.CloseChunkBagRequest1 request) {
            return base.Channel.CloseChunkBag(request);
        }
        
        public System.Guid CloseChunkBag(LexEna2BIG.KRDSiddinService.CloseChunkBagRequest CloseChunkRequest) {
            LexEna2BIG.KRDSiddinService.CloseChunkBagRequest1 inValue = new LexEna2BIG.KRDSiddinService.CloseChunkBagRequest1();
            inValue.CloseChunkRequest = CloseChunkRequest;
            LexEna2BIG.KRDSiddinService.CloseChunkBagResponse retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).CloseChunkBag(inValue);
            return retVal.CloseChunkBagResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.CloseChunkBagExResponse LexEna2BIG.KRDSiddinService.Import.CloseChunkBagEx(LexEna2BIG.KRDSiddinService.CloseChunkBagExRequest request) {
            return base.Channel.CloseChunkBagEx(request);
        }
        
        public System.Guid CloseChunkBagEx(LexEna2BIG.KRDSiddinService.CloseChunkBagRequestEx CloseChunkRequestEx) {
            LexEna2BIG.KRDSiddinService.CloseChunkBagExRequest inValue = new LexEna2BIG.KRDSiddinService.CloseChunkBagExRequest();
            inValue.CloseChunkRequestEx = CloseChunkRequestEx;
            LexEna2BIG.KRDSiddinService.CloseChunkBagExResponse retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).CloseChunkBagEx(inValue);
            return retVal.CloseChunkBagExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.GetChunkBagResponse LexEna2BIG.KRDSiddinService.Import.GetChunkBag(LexEna2BIG.KRDSiddinService.GetChunkBagRequest1 request) {
            return base.Channel.GetChunkBag(request);
        }
        
        public LexEna2BIG.KRDSiddinService.ChunkBag GetChunkBag(LexEna2BIG.KRDSiddinService.GetChunkBagRequest GetChunkBagRequest) {
            LexEna2BIG.KRDSiddinService.GetChunkBagRequest1 inValue = new LexEna2BIG.KRDSiddinService.GetChunkBagRequest1();
            inValue.GetChunkBagRequest = GetChunkBagRequest;
            LexEna2BIG.KRDSiddinService.GetChunkBagResponse retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).GetChunkBag(inValue);
            return retVal.GetChunkBagResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.GetChunkBagExResponse LexEna2BIG.KRDSiddinService.Import.GetChunkBagEx(LexEna2BIG.KRDSiddinService.GetChunkBagExRequest request) {
            return base.Channel.GetChunkBagEx(request);
        }
        
        public LexEna2BIG.KRDSiddinService.ChunkBagEx GetChunkBagEx(LexEna2BIG.KRDSiddinService.GetChunkBagRequestEx GetChunkBagRequestEx) {
            LexEna2BIG.KRDSiddinService.GetChunkBagExRequest inValue = new LexEna2BIG.KRDSiddinService.GetChunkBagExRequest();
            inValue.GetChunkBagRequestEx = GetChunkBagRequestEx;
            LexEna2BIG.KRDSiddinService.GetChunkBagExResponse retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).GetChunkBagEx(inValue);
            return retVal.GetChunkBagExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.GetRepeatFileResponse LexEna2BIG.KRDSiddinService.Import.GetRepeatFile(LexEna2BIG.KRDSiddinService.GetRepeatFileRequest1 request) {
            return base.Channel.GetRepeatFile(request);
        }
        
        public string GetRepeatFile(LexEna2BIG.KRDSiddinService.GetRepeatFileRequest GetRepeatFileRequest) {
            LexEna2BIG.KRDSiddinService.GetRepeatFileRequest1 inValue = new LexEna2BIG.KRDSiddinService.GetRepeatFileRequest1();
            inValue.GetRepeatFileRequest = GetRepeatFileRequest;
            LexEna2BIG.KRDSiddinService.GetRepeatFileResponse retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).GetRepeatFile(inValue);
            return retVal.GetRepeatFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.DownloadChunkResponse LexEna2BIG.KRDSiddinService.Import.DownloadChunk(LexEna2BIG.KRDSiddinService.DownloadChunkRequest1 request) {
            return base.Channel.DownloadChunk(request);
        }
        
        public string DownloadChunk(LexEna2BIG.KRDSiddinService.DownloadChunkRequest DownloadChunkRequest) {
            LexEna2BIG.KRDSiddinService.DownloadChunkRequest1 inValue = new LexEna2BIG.KRDSiddinService.DownloadChunkRequest1();
            inValue.DownloadChunkRequest = DownloadChunkRequest;
            LexEna2BIG.KRDSiddinService.DownloadChunkResponse retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).DownloadChunk(inValue);
            return retVal.DownloadChunkResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.GetJobsResponse LexEna2BIG.KRDSiddinService.Import.GetJobs(LexEna2BIG.KRDSiddinService.GetJobsRequest1 request) {
            return base.Channel.GetJobs(request);
        }
        
        public LexEna2BIG.KRDSiddinService.Job[] GetJobs(LexEna2BIG.KRDSiddinService.GetJobsRequest GetJobsRequest) {
            LexEna2BIG.KRDSiddinService.GetJobsRequest1 inValue = new LexEna2BIG.KRDSiddinService.GetJobsRequest1();
            inValue.GetJobsRequest = GetJobsRequest;
            LexEna2BIG.KRDSiddinService.GetJobsResponse retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).GetJobs(inValue);
            return retVal.GetJobsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.CancelJobResponse LexEna2BIG.KRDSiddinService.Import.CancelJob(LexEna2BIG.KRDSiddinService.CancelJobRequest1 request) {
            return base.Channel.CancelJob(request);
        }
        
        public void CancelJob(LexEna2BIG.KRDSiddinService.CancelJobRequest CancelJobRequest) {
            LexEna2BIG.KRDSiddinService.CancelJobRequest1 inValue = new LexEna2BIG.KRDSiddinService.CancelJobRequest1();
            inValue.CancelJobRequest = CancelJobRequest;
            LexEna2BIG.KRDSiddinService.CancelJobResponse retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).CancelJob(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LexEna2BIG.KRDSiddinService.RemoveChunkBagResponse LexEna2BIG.KRDSiddinService.Import.RemoveChunkBag(LexEna2BIG.KRDSiddinService.RemoveChunkBagRequest1 request) {
            return base.Channel.RemoveChunkBag(request);
        }
        
        public void RemoveChunkBag(LexEna2BIG.KRDSiddinService.RemoveChunkBagRequest RemoveChunkBagRequest) {
            LexEna2BIG.KRDSiddinService.RemoveChunkBagRequest1 inValue = new LexEna2BIG.KRDSiddinService.RemoveChunkBagRequest1();
            inValue.RemoveChunkBagRequest = RemoveChunkBagRequest;
            LexEna2BIG.KRDSiddinService.RemoveChunkBagResponse retVal = ((LexEna2BIG.KRDSiddinService.Import)(this)).RemoveChunkBag(inValue);
        }
    }
}
