//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexEna2BIG
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIG_Obligation
    {
        public BIG_Obligation()
        {
            this.BIG_Operacja = new HashSet<BIG_Operacja>();
        }
    
        public int BIG_ObligationId { get; set; }
        public string ObligationId { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> DataWysWezw { get; set; }
        public Nullable<System.DateTime> DataWymag { get; set; }
        public Nullable<System.DateTime> DataFaktury { get; set; }
        public Nullable<decimal> Kwota { get; set; }
        public decimal Saldo { get; set; }
        public string Opis { get; set; }
        public string Zarzuty { get; set; }
        public Nullable<System.DateTime> DataTytWyk { get; set; }
        public string Sygnatura { get; set; }
        public string Sad { get; set; }
        public Nullable<int> BIG_CaseId { get; set; }
        public string SystemId { get; set; }
        public Nullable<int> IdWienaNal { get; set; }
        public Nullable<int> TypNal { get; set; }
        public Nullable<System.DateTime> SuspendDate { get; set; }
        public Nullable<bool> AutoSuspend { get; set; }
        public Nullable<System.DateTime> NotifyDate { get; set; }
    
        public virtual BIG_Case BIG_Case { get; set; }
        public virtual ICollection<BIG_Operacja> BIG_Operacja { get; set; }
    }
}
