//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexEna2BIG
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIG_Operacja
    {
        public int BIG_OperacjaId { get; set; }
        public Nullable<System.DateTime> DataOperacji { get; set; }
        public Nullable<int> StatusOperacji { get; set; }
        public string StatOpis { get; set; }
        public Nullable<int> TypOperacji { get; set; }
        public Nullable<int> BIG_ImportId { get; set; }
        public Nullable<int> BIG_ObligationId { get; set; }
        public Nullable<int> OrderOp { get; set; }
        public Nullable<System.DateTime> DataProcedowaniaKrd { get; set; }
        public Nullable<System.DateTime> SuspendDate { get; set; }
        public Nullable<System.DateTime> NotifyDate { get; set; }
        public Nullable<int> BIG_CaseId { get; set; }
        public Nullable<int> BIG_DebtorId { get; set; }
    
        public virtual BIG_Import BIG_Import { get; set; }
        public virtual BIG_Obligation BIG_Obligation { get; set; }
        public virtual BIG_Case BIG_Case { get; set; }
        public virtual BIG_Debtor BIG_Debtor { get; set; }
    }
}
