//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexEna2BIG
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIG_Case
    {
        public BIG_Case()
        {
            this.BIG_Debtor = new HashSet<BIG_Debtor>();
            this.BIG_Obligation = new HashSet<BIG_Obligation>();
            this.BIG_Operacja = new HashSet<BIG_Operacja>();
        }
    
        public int BIG_CaseId { get; set; }
        public string CaseId { get; set; }
        public string CaseBIGId { get; set; }
        public Nullable<int> SrcSystem { get; set; }
        public Nullable<int> IdWienaSpr { get; set; }
        public Nullable<int> BIG_ImportId { get; set; }
        public Nullable<System.DateTime> SuspendDate { get; set; }
        public Nullable<System.DateTime> NotifyDate { get; set; }
    
        public virtual ICollection<BIG_Debtor> BIG_Debtor { get; set; }
        public virtual ICollection<BIG_Obligation> BIG_Obligation { get; set; }
        public virtual BIG_Import BIG_Import { get; set; }
        public virtual ICollection<BIG_Operacja> BIG_Operacja { get; set; }
    }
}
