//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexEna2BIG
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIG_Debtor
    {
        public BIG_Debtor()
        {
            this.BIG_Operacja = new HashSet<BIG_Operacja>();
        }
    
        public int BIG_DebtorId { get; set; }
        public int DebtorType { get; set; }
        public string Name { get; set; }
        public string Firstname { get; set; }
        public string Secondname { get; set; }
        public Nullable<int> IdentityNumberType { get; set; }
        public string IDNumber { get; set; }
        public string Address1L1 { get; set; }
        public string Address1L2 { get; set; }
        public string Address2L1 { get; set; }
        public string Address2L2 { get; set; }
        public string Regon { get; set; }
        public string Krs { get; set; }
        public Nullable<int> BIG_CaseId { get; set; }
        public string Pesel { get; set; }
        public string NrKlienta { get; set; }
        public string NrKlientaFull { get; set; }
    
        public virtual BIG_Case BIG_Case { get; set; }
        public virtual ICollection<BIG_Operacja> BIG_Operacja { get; set; }
    }
}
