//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexEna2BIG
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIG_Log
    {
        public int IdBIG_Log { get; set; }
        public string PackageFullId { get; set; }
        public Nullable<System.DateTime> DataOper { get; set; }
        public string MsgText { get; set; }
        public Nullable<int> TypKom { get; set; }
        public Nullable<bool> ReqResp { get; set; }
    }
}
