//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexEna2BIG
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIG_Import
    {
        public BIG_Import()
        {
            this.BIG_Operacja = new HashSet<BIG_Operacja>();
            this.BIG_Case = new HashSet<BIG_Case>();
        }
    
        public int BIG_ImportId { get; set; }
        public Nullable<System.DateTime> DataImportu { get; set; }
        public string Username { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatOpis { get; set; }
        public Nullable<System.DateTime> DataWysylki { get; set; }
        public byte[] ImportFile { get; set; }
        public Nullable<int> lPoz { get; set; }
        public string Filename { get; set; }
        public Nullable<System.Guid> JobId { get; set; }
        public Nullable<System.Guid> ChunkId { get; set; }
        public Nullable<System.DateTime> DataStatusu { get; set; }
        public Nullable<int> lBlad { get; set; }
        public Nullable<int> lSuccess { get; set; }
        public Nullable<int> TypImp { get; set; }
    
        public virtual ICollection<BIG_Operacja> BIG_Operacja { get; set; }
        public virtual ICollection<BIG_Case> BIG_Case { get; set; }
    }
}
