//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexEna2BIG
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LexEnaProEntities : DbContext
    {
        public LexEnaProEntities()
            : base("name=LexEnaProEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BIG_Case> BIG_Case { get; set; }
        public DbSet<BIG_Debtor> BIG_Debtor { get; set; }
        public DbSet<BIG_Import> BIG_Import { get; set; }
        public DbSet<BIG_Konfig> BIG_Konfig { get; set; }
        public DbSet<BIG_Log> BIG_Log { get; set; }
        public DbSet<BIG_Obligation> BIG_Obligation { get; set; }
        public DbSet<BIG_Operacja> BIG_Operacja { get; set; }
        public DbSet<UZD_Faktura> UZD_Faktura { get; set; }
        public DbSet<UZD_Pakiet> UZD_Pakiet { get; set; }
    }
}
