//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexEna2BIG
{
    using System;
    using System.Collections.Generic;
    
    public partial class UZD_Pakiet
    {
        public UZD_Pakiet()
        {
            this.UZD_Faktura = new HashSet<UZD_Faktura>();
        }
    
        public int UZD_PakietId { get; set; }
        public Nullable<System.DateTime> DataTypowania { get; set; }
        public Nullable<System.DateTime> DataPotwierdzenia { get; set; }
        public Nullable<System.DateTime> DataImportu { get; set; }
        public int Status { get; set; }
        public Nullable<int> LDlu { get; set; }
        public Nullable<int> LFaktur { get; set; }
        public Nullable<int> LPotwierdzDlu { get; set; }
        public Nullable<int> LPotwierdzFaktur { get; set; }
        public string Opis { get; set; }
        public byte[] XLSXPotwierdz { get; set; }
        public string importer { get; set; }
        public string potwierdzil { get; set; }
        public string Oznaczenie { get; set; }
    
        public virtual ICollection<UZD_Faktura> UZD_Faktura { get; set; }
    }
}
