//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LexEna2BIG
{
    using System;
    using System.Collections.Generic;
    
    public partial class UZD_Faktura
    {
        public int UZD_FakturaId { get; set; }
        public Nullable<int> IdWiena { get; set; }
        public string Sygnatura { get; set; }
        public string NrKlienta { get; set; }
        public Nullable<int> IdNalWiena { get; set; }
        public string NrFaktury { get; set; }
        public Nullable<System.DateTime> DataFaktury { get; set; }
        public Nullable<System.DateTime> DataWymagalnosci { get; set; }
        public Nullable<decimal> Kwota { get; set; }
        public Nullable<decimal> Vat { get; set; }
        public Nullable<decimal> Zaleglosc { get; set; }
        public Nullable<System.DateTime> DataZaleglosci { get; set; }
        public Nullable<int> IdDluzWiena { get; set; }
        public string Nazwa { get; set; }
        public string Miejscowosc { get; set; }
        public string Ulica { get; set; }
        public string Kod { get; set; }
        public string Nip { get; set; }
        public Nullable<System.DateTime> DataWeryfNIP { get; set; }
        public Nullable<int> StatusWalidNip { get; set; }
        public string StatusNip { get; set; }
        public int UZD_PakietId { get; set; }
        public Nullable<int> Status { get; set; }
        public string StatOpis { get; set; }
    
        public virtual UZD_Pakiet UZD_Pakiet { get; set; }
    }
}
