//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



using System;
using System.Net;
using System.Xml.Serialization;
using System.ComponentModel;
using System.Collections.ObjectModel;

namespace ZadanieTimer
{








/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.currenda.pl/epu")]
public partial class typStronaNakaz {
    
    private string nazwaField;
    
    private ulong idField;
    
    /// <remarks/>
    public string Nazwa {
        get {
            return this.nazwaField;
        }
        set {
            this.nazwaField = value;
        }
    }
    
    /// <remarks/>
    public ulong ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.currenda.pl/epu")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.currenda.pl/epu", IsNullable=false)]
public partial class NakazEPU {
    
    private typSadEPU sadEPUField;
    
    private string sygnaturaField;
    
    private string dataWplywuField;
    
    private string wSkladzieField;
    
    private string sedziaField;
    
    private string naPosiedzeniuField;
    
    private string przezField;
    
    private typStronaNakaz[] listaPowodowField;
    
    private string nakazujeAbyField;
    
    private typStronaNakaz[] listaPozwanychField;
    
    private string zaplacilPowodowiField;
    
    private typRoszczenieNakaz[] listaRoszczenField;
    
    private string wTerminieField;
    
    private string uzasadnienieField;
    
    private string sprawaWgPowodaField;
    
    private ulong idField;
    
    private string kODField;
    
    private string versionField;
    
    private string dataNakazuField;
    
    /// <remarks/>
    public typSadEPU SadEPU {
        get {
            return this.sadEPUField;
        }
        set {
            this.sadEPUField = value;
        }
    }
    
    /// <remarks/>
    public string Sygnatura {
        get {
            return this.sygnaturaField;
        }
        set {
            this.sygnaturaField = value;
        }
    }
    
    /// <remarks/>
    public string DataWplywu {
        get {
            return this.dataWplywuField;
        }
        set {
            this.dataWplywuField = value;
        }
    }
    
    /// <remarks/>
    public string WSkladzie {
        get {
            return this.wSkladzieField;
        }
        set {
            this.wSkladzieField = value;
        }
    }
    
    /// <remarks/>
    public string Sedzia {
        get {
            return this.sedziaField;
        }
        set {
            this.sedziaField = value;
        }
    }
    
    /// <remarks/>
    public string NaPosiedzeniu {
        get {
            return this.naPosiedzeniuField;
        }
        set {
            this.naPosiedzeniuField = value;
        }
    }
    
    /// <remarks/>
    public string Przez {
        get {
            return this.przezField;
        }
        set {
            this.przezField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Powod", IsNullable=false)]
    public typStronaNakaz[] ListaPowodow {
        get {
            return this.listaPowodowField;
        }
        set {
            this.listaPowodowField = value;
        }
    }
    
    /// <remarks/>
    public string NakazujeAby {
        get {
            return this.nakazujeAbyField;
        }
        set {
            this.nakazujeAbyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Pozwany", IsNullable=false)]
    public typStronaNakaz[] ListaPozwanych {
        get {
            return this.listaPozwanychField;
        }
        set {
            this.listaPozwanychField = value;
        }
    }
    
    /// <remarks/>
    public string ZaplacilPowodowi {
        get {
            return this.zaplacilPowodowiField;
        }
        set {
            this.zaplacilPowodowiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Roszczenie", IsNullable=false)]
    public typRoszczenieNakaz[] ListaRoszczen {
        get {
            return this.listaRoszczenField;
        }
        set {
            this.listaRoszczenField = value;
        }
    }
    
    /// <remarks/>
    public string WTerminie {
        get {
            return this.wTerminieField;
        }
        set {
            this.wTerminieField = value;
        }
    }
    
    /// <remarks/>
    public string Uzasadnienie {
        get {
            return this.uzasadnienieField;
        }
        set {
            this.uzasadnienieField = value;
        }
    }
    
    /// <remarks/>
    public string SprawaWgPowoda {
        get {
            return this.sprawaWgPowodaField;
        }
        set {
            this.sprawaWgPowodaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string KOD {
        get {
            return this.kODField;
        }
        set {
            this.kODField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataNakazu {
        get {
            return this.dataNakazuField;
        }
        set {
            this.dataNakazuField = value;
        }
    }
  }


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

[System.Diagnostics.DebuggerStepThroughAttribute()]

[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.currenda.pl/epu")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.currenda.pl/epu", IsNullable = false)]
public partial class Nakazy
{

    private NakazEPU[] nakazEPUField;

    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("NakazEPU")]
    public NakazEPU[] NakazEPU
    {
        get
        {
            return this.nakazEPUField;
        }
        set
        {
            this.nakazEPUField = value;
        }
    }

    }
}