using System.Xml.Serialization;
using System.Linq;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System;
using System.Xml.Schema;
using System.IO;



// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace ZadanieTimer
{



/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.currenda.pl/epu")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.currenda.pl/epu", IsNullable=false)]
public partial class OrzeczenieEPU {
    
    private typSadEPU sadEPUField;
    
    private string sygnaturaField;
    
    private string dataWplywuField;
    
    private string wSkladzieField;
    
    private string sedziaField;
    
    private string naPosiedzeniuField;
    
    private string przezField;
    
    private typStronaNakaz[] listaPowodowField;
    
    private string nakazujeAbyField;
    
    private typStronaNakaz[] listaPozwanychField;
    
    private string naSkutekField;
    
    private string postanawiaField;
    
    private string trescField;
    
    private string uzasadnienieField;
    
    private typNakaz nakazField;
    
    private string sprawaWgPowodaField;
    
    private string nrTytuluWykonField;
    
    private string celEgzekucjiField;
    
    private string celEgzekucjiTekstField;
    
    private ulong idField;
    
    private string kODField;
    
    private string versionField;
    
    private string dataOrzeczeniaField;
    
    private sbyte kodDecyzjiField;
    
    private string nazwaOrzeczeniaField;
    
    /// <remarks/>
    public typSadEPU SadEPU {
        get {
            return this.sadEPUField;
        }
        set {
            this.sadEPUField = value;
        }
    }
    
    /// <remarks/>
    public string Sygnatura {
        get {
            return this.sygnaturaField;
        }
        set {
            this.sygnaturaField = value;
        }
    }
    
    /// <remarks/>
    public string DataWplywu {
        get {
            return this.dataWplywuField;
        }
        set {
            this.dataWplywuField = value;
        }
    }
    
    /// <remarks/>
    public string WSkladzie {
        get {
            return this.wSkladzieField;
        }
        set {
            this.wSkladzieField = value;
        }
    }
    
    /// <remarks/>
    public string Sedzia {
        get {
            return this.sedziaField;
        }
        set {
            this.sedziaField = value;
        }
    }
    
    /// <remarks/>
    public string NaPosiedzeniu {
        get {
            return this.naPosiedzeniuField;
        }
        set {
            this.naPosiedzeniuField = value;
        }
    }
    
    /// <remarks/>
    public string Przez {
        get {
            return this.przezField;
        }
        set {
            this.przezField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Powod", IsNullable=false)]
    public typStronaNakaz[] ListaPowodow {
        get {
            return this.listaPowodowField;
        }
        set {
            this.listaPowodowField = value;
        }
    }
    
    /// <remarks/>
    public string NakazujeAby {
        get {
            return this.nakazujeAbyField;
        }
        set {
            this.nakazujeAbyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Pozwany", IsNullable=false)]
    public typStronaNakaz[] ListaPozwanych {
        get {
            return this.listaPozwanychField;
        }
        set {
            this.listaPozwanychField = value;
        }
    }
    
    /// <remarks/>
    public string NaSkutek {
        get {
            return this.naSkutekField;
        }
        set {
            this.naSkutekField = value;
        }
    }
    
    /// <remarks/>
    public string Postanawia {
        get {
            return this.postanawiaField;
        }
        set {
            this.postanawiaField = value;
        }
    }
    
    /// <remarks/>
    public string Tresc {
        get {
            return this.trescField;
        }
        set {
            this.trescField = value;
        }
    }
    
    /// <remarks/>
    public string Uzasadnienie {
        get {
            return this.uzasadnienieField;
        }
        set {
            this.uzasadnienieField = value;
        }
    }
    
    /// <remarks/>
    public typNakaz Nakaz {
        get {
            return this.nakazField;
        }
        set {
            this.nakazField = value;
        }
    }
    
    /// <remarks/>
    public string SprawaWgPowoda {
        get {
            return this.sprawaWgPowodaField;
        }
        set {
            this.sprawaWgPowodaField = value;
        }
    }
    
    /// <remarks/>
    public string NrTytuluWykon {
        get {
            return this.nrTytuluWykonField;
        }
        set {
            this.nrTytuluWykonField = value;
        }
    }
    
    /// <remarks/>
    public string CelEgzekucji {
        get {
            return this.celEgzekucjiField;
        }
        set {
            this.celEgzekucjiField = value;
        }
    }
    
    /// <remarks/>
    public string CelEgzekucjiTekst {
        get {
            return this.celEgzekucjiTekstField;
        }
        set {
            this.celEgzekucjiTekstField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public ulong ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string KOD {
        get {
            return this.kODField;
        }
        set {
            this.kODField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dataOrzeczenia {
        get {
            return this.dataOrzeczeniaField;
        }
        set {
            this.dataOrzeczeniaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public sbyte kodDecyzji {
        get {
            return this.kodDecyzjiField;
        }
        set {
            this.kodDecyzjiField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string nazwaOrzeczenia {
        get {
            return this.nazwaOrzeczeniaField;
        }
        set {
            this.nazwaOrzeczeniaField = value;
        }
    }
 }

[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

[System.Diagnostics.DebuggerStepThroughAttribute()]

[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.currenda.pl/epu")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.currenda.pl/epu", IsNullable = false)]
public partial class Postanowienia
{

    private OrzeczenieEPU[] orzeczenieEPUField;


    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrzeczenieEPU")]
    public OrzeczenieEPU[] OrzeczenieEPU
    {
        get
        {
            return this.orzeczenieEPUField;
        }
        set
        {
            this.orzeczenieEPUField = value;
        }
    }

}
}