//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//-----------------------------------------------------------------------------

using System.Xml.Serialization;
using System.Linq;
using System.Collections.ObjectModel;
using System.ComponentModel;
using System;
using System.Xml.Schema;
using System.IO;






// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace ZadanieTimer
{

    /// <remarks/>
   
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    //[XmlAttribute(Namespace = "www.diranieh.com")]

    [XmlRoot(Namespace = "http://www.currenda.pl/epu")]


    public partial class PozewEPU : INotifyPropertyChanged
    {
        public event PropertyChangedEventHandler PropertyChanged;
        private string oswiadczenieField;
        private typAdresat adresatField;
        private typAdresat sadWlasciwyField;
        private typSkladajacy osobaSkladajacaField;
        private ObservableCollection<typStrona> listaPowodowField;
        private ObservableCollection<typStrona> listaPozwanychField;
        private string sprawaWgPowodaField;
        private decimal wartoscSporuField;
        private typOplata oplataSadowaField;
        private typKoszty kosztyZastepstwaField;
        private typKoszty inneKosztyField;
        private typRachunekDoZwrotuOplat rachunekDoZwrotuOplatField;
        private ObservableCollection<typRoszczenie> listaRoszczenField;
        private typRoszczenie currentRoszczenieField;  // aktualnie wybrane roszczenie
        private ObservableCollection<typDowod> listaDowodowField;
        private string inneRoszczeniaField;
        private string uzasadnienieField;
        private ObservableCollection<typOsoba> listaPodpisowField;
        private long idField;
        private string versionField;
        private DateTime dataZlozeniaField;




        // Wypełnianie wartości przedmiotu sporu
        public void ObliczSumy()
        {
            decimal suma = 0;
            decimal odsKapital = 0;
            decimal odsNalicz = 0;
            bool isOdsKapital = false;

            /*
            if (this.OdsetkiSkapitalizowne != null)
            {
                foreach (typDowoduOds tods in this.OdsetkiSkapitalizowne.Dowod)
                {
                    odsNalicz += (tods.Odsetki == null ? 0 : Convert.ToDecimal(tods.Odsetki));
                
                }
            
            }
            */
            if (this.listaRoszczenField != null)
            {
                suma = 0;

                foreach (typRoszczenie typro in this.listaRoszczenField)
                {
                    suma += typro.Wartosc;
                    isOdsKapital = false;
                    if (typro.Opis.Contains("noty odsetkowej"))
                        isOdsKapital = true;
                    if (isOdsKapital == true && typro.Dowody.Count > 0)
                    {
                        foreach (typDowod td in this.ListaDowodow)
                        {
                            if (typro.Dowody.Contains(td.Numer) && td.TypDowodu == typRodzajDowodu.faktura)
                            {
                                isOdsKapital = false;
                                break;
                            }
                        }
                    }
                    if (isOdsKapital == true)
                        odsKapital += typro.Wartosc;


                }
            }
            this.OdsKapital = odsKapital;
            this.WartoscSporu = suma;
            this.OdsNalicz = odsNalicz;
            this.OplataSadowa.WartoscOplaty = EPUCalc.countOplata(suma);

        }

        public decimal ObliczKzp(decimal WPS)
        {
            if (this.KosztyZastepstwa.Zasadzenie > 0)
            {
                if (this.KosztyZastepstwa.WgNorm == 1) // jeśli wg norm
                    return EPUCalc.countKZP(WPS);
                else
                    return this.KosztyZastepstwa.Wartosc;
            }
            else
                return 0;


        }



        protected virtual void OnPropertyChanged(PropertyChangedEventArgs args)
        {
            PropertyChangedEventHandler handler = this.PropertyChanged;
            if (handler != null)
            {
                handler(this, args);
            }
        }

        private void OnPropertyChanged(string propertyName)
        {
            this.OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }


        private void SaveDowody()
        { // Zachowanie dowodów dla starego 
            if (currentRoszczenieField != null)
            {
                if (currentRoszczenieField.Dowody != null)
                    currentRoszczenieField.Dowody.Clear();
                try
                {
                    foreach (typDowod dow in listaDowodowField)
                    {
                        if (dow.IsSelected)
                        {
                            currentRoszczenieField.Dowody.Add(dow.Numer);
                        }
                    }
                }

                finally { ;}
            }

        }

        private void LoadDowody()
        {// odznaczenie dowodów  docelowo - za pomocą LinQ

            // ustawianie check box'ów   
            if (listaDowodowField != null)
            {
                foreach (typDowod dow in listaDowodowField)
                {
                    dow.IsSelected = false;
                }
                if (currentRoszczenieField.Dowody == null)
                    currentRoszczenieField.Dowody = new ObservableCollection<int>();
                if (currentRoszczenieField.Dowody != null)
                {
                    foreach (int d in currentRoszczenieField.Dowody)
                    {
                        foreach (typDowod dow in listaDowodowField)
                        {
                            if ((int)dow.Numer == d)
                            {
                                dow.IsSelected = true;
                                break;
                            }
                        }
                    }
                }
            }

        }

        public PozewEPU()
        {

            /* this.versionField = "1.0";
            this.dataZlozeniaField = DateTime.Today;
            this.oplataSadowaField = new typOplata();
            this.kosztyZastepstwaField = new typKoszty();
            this.inneKosztyField = new typKoszty();
            this.listaPowodowField = new ObservableCollection<typStrona>();
            this.listaPozwanychField = new ObservableCollection<typStrona>();
            this.osobaSkladajacaField = new typSkladajacy();
            this.osobaSkladajacaField.Osoba = new typOsoba();
            this.osobaSkladajacaField.Adres = new typAdres();
            this.Adresat = new typAdresat();
            this.Adresat.Adres = new typAdres();

            this.kosztyZastepstwaField.WgNorm = 1;
            */
        }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public decimal OdsKapital { get; set; }
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public decimal OdsNalicz { get; set; }


        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public typRoszczenie CurrentRoszczenie
        {
            get
            {
                return this.currentRoszczenieField;
            }
            set
            {
                if (this.currentRoszczenieField != value)
                {
                    // new Observebel Collection ..........= 
                    if (currentRoszczenieField != null)
                        if (currentRoszczenieField.Dowody != null)
                            SaveDowody();


                    this.currentRoszczenieField = value;

                    if (currentRoszczenieField != null)
                    {
                        if (currentRoszczenieField.Dowody == null) currentRoszczenieField.Dowody = new ObservableCollection<int>();
                        if (currentRoszczenieField.Odsetki == null) currentRoszczenieField.Odsetki = new ObservableCollection<typOkresOdsetkowy>();
                        LoadDowody();

                    }
                    this.ObliczSumy();
                }
            }
        }
        public string Oswiadczenie
        {
            get
            {
                return this.oswiadczenieField;
            }
            set
            {
                this.oswiadczenieField = value;
                this.OnPropertyChanged("Oswiadczenie");
            }
        }
        /// <remarks/>
        public typAdresat Adresat
        {
            get
            {
                return this.adresatField;
            }
            set
            {
                if (this.adresatField != value)
                {
                    this.adresatField = value;
                    this.OnPropertyChanged("Adresat");
                }
            }
        }

        /// <remarks/>
        public typAdresat SadWlasciwy
        {
            get
            {
                return this.sadWlasciwyField;
            }
            set
            {
                this.sadWlasciwyField = value;
            }
        }

        
        /// <remarks/>
        public typSkladajacy OsobaSkladajaca
        {
            get
            {
                return this.osobaSkladajacaField;
            }
            set
            {

                this.osobaSkladajacaField = value;
                this.OnPropertyChanged("OsobaSkaldajaca");
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Powod", IsNullable = false)]
        public ObservableCollection<typStrona> ListaPowodow
        {
            get
            {
                return this.listaPowodowField;
            }
            set
            {
                if (this.listaPowodowField != value)
                {
                    this.listaPowodowField = value;
                    this.OnPropertyChanged("ListPowodow");
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Pozwany", IsNullable = false)]
        public ObservableCollection<typStrona> ListaPozwanych
        {
            get
            {
                return this.listaPozwanychField;
            }
            set
            {
                if (this.listaPowodowField != value)
                {
                    this.listaPozwanychField = value;
                    this.OnPropertyChanged("ListaPozwanych");
                }
            }
        }

        /// <remarks/>
        public string SprawaWgPowoda
        {
            get
            {
                return this.sprawaWgPowodaField;
            }
            set
            {
                if (this.sprawaWgPowodaField != value)
                {
                    this.sprawaWgPowodaField = value;
                    this.OnPropertyChanged(SprawaWgPowoda);
                }
            }
        }

        /// <remarks/>
        public decimal WartoscSporu
        {
            get
            {
                return this.wartoscSporuField;
            }
            set
            {
                if (this.wartoscSporuField != value)
                {
                    this.wartoscSporuField = value;
                    OnPropertyChanged("WartoscSporu");
                }

            }
        }

        /// <remarks/>
        [XmlElement(ElementName = "OplataSadowa")]
        public typOplata OplataSadowa
        {
            get
            {
                return this.oplataSadowaField;
            }
            set
            {
                if (oplataSadowaField != value)
                {
                    this.oplataSadowaField = value;
                    this.OnPropertyChanged("OplataSadowa");
                }
            }
        }

        /// <remarks/>
        public typKoszty KosztyZastepstwa
        {
            get
            {
                return this.kosztyZastepstwaField;
            }
            set
            {

                this.kosztyZastepstwaField = value;
                this.OnPropertyChanged("KosztyZastepstwa");
            }
        }

        /// <remarks/>
        public typKoszty InneKoszty
        {
            get
            {
                return this.inneKosztyField;
            }
            set
            {
                this.inneKosztyField = value;
                this.OnPropertyChanged("InneKoszty");
            }
        }

        public typRachunekDoZwrotuOplat RachunekDoZwrotuOplat
        {
            get
            {
                return this.rachunekDoZwrotuOplatField;
            }
            set
            {
                this.rachunekDoZwrotuOplatField = value;
                this.OnPropertyChanged("RachunekDoZwrotuOplat");
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Roszczenie", IsNullable = false)]
        public ObservableCollection<typRoszczenie> ListaRoszczen
        {
            get
            {
                return this.listaRoszczenField;
            }
            set
            {
                this.listaRoszczenField = value;
                if (this.listaRoszczenField != null)
                {
                    this.wartoscSporuField = 0;
                    foreach (typRoszczenie typro in this.listaRoszczenField)
                        this.wartoscSporuField += typro.Wartosc;

                }
            }

        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Dowod", IsNullable = false)]
        public ObservableCollection<typDowod> ListaDowodow
        {
            get
            {
                return this.listaDowodowField;
            }
            set
            {
                this.listaDowodowField = value;
            }
        }





        /// <remarks/>
        public string InneRoszczenia
        {
            get
            {
                return this.inneRoszczeniaField;
            }
            set
            {
                if (this.inneRoszczeniaField != value)
                {
                    this.inneRoszczeniaField = value;
                    this.OnPropertyChanged("InneRoszczenia");
                }
            }
        }

        
        /// <remarks/>
        public string Uzasadnienie
        {
            get
            {
                return this.uzasadnienieField;
            }
            set
            {
                if (this.uzasadnienieField != value)
                {
                    this.uzasadnienieField = value;
                    this.OnPropertyChanged("Uzasadnienie");
                }
            }
        }
        [System.Xml.Serialization.XmlArrayItemAttribute("Podpis", IsNullable = false)]
        public ObservableCollection<typOsoba> ListaPodpisow
        {
            get
            {
                return this.listaPodpisowField;

            }
            set
            {
                this.listaPodpisowField = value;
                this.OnPropertyChanged("ListaPodpisow");
            }
        }
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                if (this.idField != value)
                {
                    this.idField = value;
                    this.OnPropertyChanged("ID");
                }
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                if (this.versionField != value)
                {
                    this.versionField = value;
                    this.OnPropertyChanged("version");
                }
            }
        }

        /// <remarks/>
        [XmlIgnoreAttribute()]
        public DateTime DataZlozenia
        {
            get
            {
                return this.dataZlozeniaField;
            }
            set
            {
                if (this.dataZlozeniaField != value)
                {
                    this.dataZlozeniaField = value;
                    this.OnPropertyChanged("DataZlozenia");
                }
            }
        }
        // serializacja do XML'a
        [XmlAttribute("dataZlozenia")]
        public string XmlDateTime
        {


            get { return this.DataZlozenia.ToString("yyyy-MM-dd"); }
            set { this.DataZlozenia = Convert.ToDateTime(value); }
        }
        /*
        [XmlIgnore]
        public typSprawaOds  OdsetkiSkapitalizowne
        { get; set; }
        */

    }


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]

    [System.Diagnostics.DebuggerStepThroughAttribute()]

    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.currenda.pl/epu")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.currenda.pl/epu", IsNullable = false)]
    public partial class Pozwy
    {

        private PozewEPU[] pozewEPUField;

        private string oznaczeniePaczkiField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PozewEPU")]
        public PozewEPU[] PozewEPU
        {
            get
            {
                return this.pozewEPUField;
            }
            set
            {
                this.pozewEPUField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string OznaczeniePaczki
        {
            get
            {
                return this.oznaczeniePaczkiField;
            }
            set
            {
                this.oznaczeniePaczkiField = value;
            }
        }





    }
}
